import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { defaultConfig, loadConfig } from "../src/config.js";

describe("loadConfig", () => {
  it("uses the bundled rules when no config file exists", async () => {
    const directory = await mkdtemp(join(tmpdir(), "jevlint-config-"));

    const config = await loadConfig({ cwd: directory });

    expect(Object.keys(config.rules)).toEqual([
      // BEGIN GENERATED: rule-keys (src/defaults.ts order; do not edit — run pnpm generate:registry)
      "jev/no-hidden-input-mutation",
      "jev/no-hidden-io",
      "jev/no-lossy-sentinel-return",
      "jev/no-query-side-effect",
      "jev/no-narrating-comment",
      "jev/no-pass-through-wrapper",
      "jev/no-mysterious-name",
      "jev/no-speculative-generality",
      "jev/no-ad-hoc-branching",
      "jev/no-mixed-responsibilities",
      "jev/no-data-clump",
      "jev/no-scattered-policy",
      "jev/no-correlated-state-booleans",
      "jev/no-unconstrained-state-string",
      "jev/no-conditionally-valid-state",
      "jev/no-needless-abstraction",
      "jev/no-generic-magic",
      "jev/no-disproportionate-configuration",
      "jev/no-avoidable-orchestration",
      "jev/no-hidden-runtime-input",
      "jev/no-hidden-initialization-order",
      "jev/no-implicit-atomicity",
      "jev/no-complexity-displacement",
      "jev/no-transport-coupled-domain",
      "jev/no-persistence-model-leak",
      "jev/no-interchangeable-domain-primitives",
      "jev/no-domain-policy-in-adapter",
      "jev/no-swallowed-error",
      "jev/no-lossy-error-translation",
      "jev/no-unsafe-retry",
      "jev/no-hidden-partial-failure",
      "jev/no-duplicated-logic",
      "jev/no-type-code-dispatch",
      "jev/no-mode-flag-parameter",
      "jev/no-message-chain",
      "jev/no-mixed-abstraction-levels",
      "jev/no-unvalidated-boundary-shape",
      "jev/no-stale-binding-use",
      "jev/no-pre-gate-side-effect",
      "jev/no-inverted-authorization-predicate",
      "jev/no-hardcoded-config-shadow",
      "jev/no-sibling-identifier-swap",
      "jev/no-feature-envy",
      "jev/no-foreign-mutation",
      "jev/no-temporal-call-coupling",
      "jev/no-shotgun-change",
      "jev/no-undocumented-contract",
      "jev/no-unbounded-wait",
      "jev/no-detached-async-work",
      "jev/no-shared-mutable-module-state",
      "jev/no-type-checker-escape",
      "jev/no-unawaited-iteration-work",
      "jev/no-asymmetric-normalization",
      "jev/no-unguarded-nullable-dereference",
      "jev/no-falsy-absent-conflation",
      "jev/no-unanchored-domain-check",
      "jev/no-contract-signature-drift",
      "jev/no-accidental-serialization",
      "jev/no-discarded-transformation",
      "jev/no-load-bearing-async",
      "jev/no-untrusted-sink-input",
      "jev/no-unreleased-subscription",
      "jev/no-unwieldy-signature",
      "jev/no-inappropriate-intimacy",
      "jev/no-anemic-type",
      "jev/no-temporary-field",
      "jev/no-low-cohesion-class",
      "jev/no-divergent-change",
      "jev/no-divergent-sibling-interfaces",
      "jev/no-refused-inheritance",
      "jev/no-unnamed-parameter-object",
      "jev/no-predictable-token",
      "jev/no-unreachable-guard",
      "jev/no-unaccountable-todo",
      "jev/no-adversarial-regex",
      "jev/no-live-credential",
      "jev/no-output-argument",
      "jev/no-contextless-error",
      "jev/no-unchecked-precondition",
      "jev/no-unenforced-warning-comment",
      "jev/no-table-shaped-conditional",
      "jev/no-sequential-step-soup",
      "jev/no-mirrored-derived-state",
      "jev/no-construction-in-use",
      "jev/no-retry-storm-shape",
      "jev/no-unbounded-accumulation",
      "jev/no-call-in-loop-persistence",
      "jev/no-unbounded-parallel-fanout",
      "jev/no-concurrent-shared-mutation",
      "jev/no-sensitive-data-in-log",
      "jev/no-unsafe-redirect-target",
      "jev/no-overbroad-origin-trust",
      "jev/no-path-traversal-join",
      "jev/no-phantom-member-access",
      "jev/no-laundered-absence",
      "jev/no-unverified-claim",
      "jev/no-convention-breaking-addition",
      "jev/no-repeated-handler-preamble",
      "jev/no-non-narrowing-guard",
      "jev/no-excess-context-parameter",
      "jev/no-shallow-convenience-layer",
      "jev/no-prototype-in-production",
      "jev/no-hidden-loop-exit",
      "jev/no-inconsistent-error-contract",
      "jev/no-breaking-export-reshape",
      "jev/no-positional-extension-drift",
      "jev/no-mixed-absence-convention",
      "jev/no-shared-mutable-default",
      "jev/no-blocking-event-loop-call",
      "jev/no-unguarded-async-init",
      "jev/no-promise-combinator-mismatch",
      "jev/no-orphaned-timer",
      "jev/no-unsynchronized-shared-memory",
      "jev/no-timezone-naive-arithmetic",
      "jev/no-floating-money-arithmetic",
      "jev/no-offset-pagination-drift",
      "jev/no-unit-scale-mismatch",
      "jev/no-truncating-numeric-parse",
      "jev/no-locale-date-serialization",
      "jev/no-overload-resolution-ambiguity",
      "jev/no-sync-async-sibling-ambiguity",
      "jev/no-leaky-internal-export",
      "jev/no-weak-crypto-primitive",
      "jev/no-disabled-tls-verification",
      "jev/no-dynamic-code-execution",
      "jev/no-locale-blind-ordering",
      "jev/no-cascading-fallback",
      "jev/no-silent-queue-drop",
      "jev/no-missing-shutdown-drain",
      "jev/no-missing-health-signal",
      "jev/no-deployment-coupled-assumption",
      "jev/no-assertion-free-test",
      "jev/no-sleep-in-test",
      "jev/no-logic-in-test",
      "jev/no-mock-everything",
      "jev/no-duplicated-fixture-drift",
      "jev/no-stale-feature-flag",
      "jev/no-unlabeled-interactive-element",
      "jev/no-unlocalized-user-string",
      "jev/no-console-residue",
      "jev/no-deep-happy-path-nesting",
      "jev/no-drilled-prop",
      "jev/no-stale-comment",
      "jev/no-paraphrased-sibling-logic",
      "jev/no-unclosed-handle",
      "jev/no-bespoke-crypto-construction",
      "jev/no-duplicated-style-object",
      "jev/no-unmeasured-performance-machinery",
      "jev/no-unmigrated-schema-change",
      "jev/no-unconsumed-telemetry",
      "jev/no-english-only-pluralization",
      "jev/no-duplicate-config-source",
      "jev/no-unowned-feature-flag",
      "jev/no-superseded-api-use",
      "jev/no-phantom-package-import",
      "jev/no-interaction-pinning-test",
      "jev/no-single-use-dependency",
      "jev/no-second-shelf-dependency",
      "jev/no-repeated-test-preamble",
      "jev/no-unpinned-boundary-branch",
      "jev/no-client-only-authorization",
      "jev/no-check-then-act-race",
      "jev/no-non-idempotent-retry",
      "jev/no-parallel-abstraction",
      "jev/no-misplaced-error-boundary",
      "jev/no-rare-case-first",
      "jev/no-side-effecting-conditional-expression",
      "jev/no-unexplained-complex-condition",
      "jev/no-clever-expression",
      "jev/no-hand-rolled-group-by",
      "jev/no-hand-rolled-deep-clone",
      "jev/no-hand-rolled-set-ops",
      "jev/no-hand-rolled-flatten",
      "jev/no-hand-rolled-deep-equal",
      "jev/no-hand-rolled-schema-check",
      "jev/no-hand-rolled-retry-loop",
      "jev/no-hand-rolled-concurrency-limit",
      "jev/no-hand-rolled-debounce",
      "jev/no-hand-rolled-csv-split",
      "jev/no-nested-conditional-expression",
      "jev/no-unexplained-behavioral-literal",
      "jev/no-shadowed-meaning",
      "jev/no-oversized-working-set",
      "jev/no-hand-rolled-date-format",
      "jev/no-hand-rolled-relative-time",
      "jev/no-hand-rolled-number-format",
      "jev/no-hand-rolled-url-query",
      "jev/no-far-away-test",
      "jev/no-utils-grab-bag-growth",
      "jev/no-barrel-bypass",
      "jev/no-skipped-level-import",
      "jev/no-deep-delegation-chain",
      "jev/no-stability-inversion",
      "jev/no-options-style-split",
      "jev/no-concrete-stable-module",
      "jev/no-import-use-skew",
      "jev/no-unverified-mock-contract",
      "jev/no-implementation-mirrored-expectation",
      "jev/no-self-authored-exam",
      "jev/no-change-stranded-code",
      "jev/no-impossible-error-branch",
      "jev/no-retained-superseded-implementation",
      "jev/no-doubled-pure-helper",
      "jev/no-import-cycle-tangle",
      "jev/no-domain-upward-import",
      "jev/no-barrel-wide-reexport",
      "jev/no-utility-module-grab-bag",
      "jev/no-duplicate-module-role",
      "jev/no-clone-and-tweak-sibling",
      "jev/no-single-caller-exported-helper",
      "jev/no-string-duplicated-enumeration",
      "jev/no-convergent-twin-types",
      "jev/no-change-amplifier-case",
      "jev/no-mutable-surface-expansion",
      "jev/no-subclass-fragility-hook",
      "jev/no-contract-narrowing-after-ship",
      "jev/no-nondeterministic-test-input",
      "jev/no-untestable-singleton-grab",
      "jev/no-giant-test-arrange",
      "jev/no-private-internals-assertion",
      "jev/no-flaky-order-assertion",
      "jev/no-redundant-conditional-arm",
      "jev/no-double-negation",
      "jev/no-hollow-delegation-chain",
      "jev/no-transitive-plumbing",
      "jev/no-distrustful-type-guard",
      "jev/no-divergent-inverses",
      "jev/no-lopsided-error-handling",
      "jev/no-repeated-predicate",
      "jev/no-overloaded-boolean-return",
      "jev/no-parallel-enumerations",
      "jev/no-synonym-vocabulary",
      "jev/no-knob-multiplicity",
      "jev/no-boolean-fanout",
      "jev/no-hand-rolled-uuid",
      "jev/no-hand-rolled-promise-timeout",
      "jev/no-hand-rolled-event-bus",
      "jev/no-hand-rolled-fetch-wrapper",
      "jev/no-fs-recursive-reinvent",
      "jev/no-hand-rolled-string-hash",
      "jev/no-mystery-literal-argument",
      "jev/no-unexplained-domain-threshold",
      "jev/no-verbless-function-name",
      "jev/no-misdirecting-error-message",
      "jev/no-ambiguous-positional-siblings",
      "jev/no-deceptive-name",
      "jev/no-punned-name",
      "jev/no-cryptic-abbreviation",
      "jev/no-negative-boolean-name",
      "jev/no-unitless-quantity",
      "jev/no-layer-skipping-call",
      "jev/no-chatty-interface",
      "jev/no-partitioned-fat-interface",
      "jev/no-dev-dependency-runtime-leak",
      "jev/no-cross-module-call-order",
      "jev/no-callback-return-split",
      "jev/no-reentrant-entry",
      "jev/no-implementation-type-in-signature",
      "jev/no-unversioned-envelope-change",
      "jev/no-context-homonym-type",
      "jev/no-wide-fan-in-edit",
      "jev/no-unpinned-failure-path",
      "jev/no-incidental-snapshot",
      "jev/no-quarantined-test-coverage",
      "jev/no-flag-shepherded-control-flow",
      "jev/no-inline-lifecycle-phases",
      "jev/no-unused-exported-helper",
      "jev/no-commented-out-implementation",
      "jev/no-unmarked-abandoned-compat-layer",
      "jev/no-variant-partitioned-helper",
      "jev/no-coincidental-similarity",
      "jev/no-entangled-mechanical-change",
      "jev/no-predicate-name-deception",
      "jev/no-confusion-confessing-comment",
      "jev/no-unexplained-suppression",
      "jev/no-ambient-dependency-grab",
      "jev/no-singly-owned-lazy-shared-state",
      "jev/no-unit-ambiguous-quantity",
      "jev/no-partially-narrowed-nullable",
      "jev/no-heterogeneous-primitive-callers",
      "jev/no-cross-area-export-break",
      "jev/no-efferent-coupling-burst",
      "jev/no-stable-to-volatile-edge",
      "jev/no-new-foreign-state-write-edge",
      "jev/no-shared-kernel-new-consumer",
      "jev/no-direction-reversing-edge",
      "jev/no-cross-context-test-reach",
      "jev/no-twin-gateway-emergence",
      "jev/no-unwrapped-service-edge",
      "jev/no-unpinned-compat-quirk",
      "jev/no-hidden-collaborator-read",
      "jev/no-mixed-calculation-and-interaction",
      "jev/no-fragmented-stateful-procedure",
      "jev/no-stable-surface-widening",
      "jev/no-team-boundary-crossing",
      "jev/no-cross-service-source-reach",
      "jev/no-same-stem-divergent-role",
      "jev/no-non-exhaustive-domain-handling",
      "jev/no-misplaced-coordination",
      "jev/no-coupled-index-collections",
      "jev/no-log-and-propagate",
      // END GENERATED: rule-keys
    ]);
  });

  it("rejects retired threshold and severity settings", async () => {
    const directory = await mkdtemp(join(tmpdir(), "jevlint-config-"));
    await writeFile(
      join(directory, "jevlint.config.ts"),
      `export default {
        rules: {
          "personal/invalid": {
            scope: "function",
            question: { instructions: "Is this invalid?" },
            threshold: 2,
            severity: "warning",
            message: "Invalid threshold."
          }
        }
      }`,
    );

    await expect(loadConfig({ cwd: directory })).rejects.toThrow();
  });

  it("loads TypeScript config and allows bundled rules to be disabled", async () => {
    const directory = await mkdtemp(join(tmpdir(), "jevlint-config-"));
    const configPath = join(directory, "jevlint.config.ts");
    await writeFile(
      configPath,
      `export default {
        rules: {
          "jev/no-narrating-comment": "off"
        }
      }`,
    );

    const config = await loadConfig({ cwd: directory });

    expect(config.rules["jev/no-narrating-comment"]).toBeUndefined();
    expect(config.rules["jev/no-pass-through-wrapper"]).toEqual(
      defaultConfig.rules["jev/no-pass-through-wrapper"],
    );
  });

  it("rejects rules keys that match no bundled or plugin rule", async () => {
    const directory = await mkdtemp(join(tmpdir(), "jevlint-config-"));
    await writeFile(
      join(directory, "jevlint.config.ts"),
      `export default {
        rules: {
          "personal/suspicious-name": {
            scope: "function",
            question: { instructions: "Is this function misleadingly named?" },
            message: "Function name does not match its behavior."
          }
        }
      }`,
    );

    await expect(loadConfig({ cwd: directory })).rejects.toThrow(
      /jevlint: unknown rule "personal\/suspicious-name"\. Did you mean ".+"\?/,
    );
  });
});
