import { describe, expect, it } from "vitest";
import { defaultConfig } from "../src/config.js";

const extractedRules = [
  ["jev/no-mysterious-name", "function"],
  ["jev/no-narrating-comment", "comment"],
  ["jev/no-foreign-mutation", "function"],
  ["jev/no-temporal-call-coupling", "function"],
  ["jev/no-shotgun-change", "change"],
  ["jev/no-undocumented-contract", "function"],
  ["jev/no-accidental-serialization", "function"],
  ["jev/no-discarded-transformation", "function"],
  ["jev/no-load-bearing-async", "function"],
  ["jev/no-untrusted-sink-input", "function"],
  ["jev/no-unreleased-subscription", "function"],
  ["jev/no-speculative-generality", "function"],
  ["jev/no-ad-hoc-branching", "function"],
  ["jev/no-feature-envy", "function"],
  ["jev/no-duplicated-logic", "function"],
  ["jev/no-type-code-dispatch", "function"],
  ["jev/no-mode-flag-parameter", "function"],
  ["jev/no-message-chain", "function"],
  ["jev/no-mixed-abstraction-levels", "function"],
  ["jev/no-unbounded-wait", "function"],
  ["jev/no-detached-async-work", "function"],
  ["jev/no-shared-mutable-module-state", "abstraction"],
  ["jev/no-type-checker-escape", "function"],
  ["jev/no-unawaited-iteration-work", "function"],
  ["jev/no-asymmetric-normalization", "function"],
  ["jev/no-unguarded-nullable-dereference", "function"],
  ["jev/no-falsy-absent-conflation", "function"],
  ["jev/no-unanchored-domain-check", "function"],
  ["jev/no-contract-signature-drift", "function"],
  ["jev/no-unwieldy-signature", "function"],
  ["jev/no-inappropriate-intimacy", "function"],
  ["jev/no-anemic-type", "abstraction"],
  ["jev/no-temporary-field", "abstraction"],
  ["jev/no-low-cohesion-class", "abstraction"],
  ["jev/no-divergent-change", "change"],
  ["jev/no-divergent-sibling-interfaces", "abstraction"],
  ["jev/no-refused-inheritance", "abstraction"],
  ["jev/no-unnamed-parameter-object", "function"],
  ["jev/no-predictable-token", "function"],
  ["jev/no-unreachable-guard", "function"],
  ["jev/no-unaccountable-todo", "comment"],
  ["jev/no-adversarial-regex", "function"],
  ["jev/no-live-credential", "function"],
  ["jev/no-unvalidated-boundary-shape", "function"],
  ["jev/no-stale-binding-use", "function"],
  ["jev/no-pre-gate-side-effect", "function"],
  ["jev/no-inverted-authorization-predicate", "function"],
  ["jev/no-hardcoded-config-shadow", "function"],
  ["jev/no-sibling-identifier-swap", "function"],
  ["jev/no-output-argument", "function"],
  ["jev/no-contextless-error", "function"],
  ["jev/no-unchecked-precondition", "function"],
  ["jev/no-unenforced-warning-comment", "comment"],
  ["jev/no-table-shaped-conditional", "function"],
  ["jev/no-sequential-step-soup", "function"],
  ["jev/no-mirrored-derived-state", "function"],
  ["jev/no-construction-in-use", "function"],
  ["jev/no-retry-storm-shape", "function"],
  ["jev/no-unbounded-accumulation", "function"],
  ["jev/no-call-in-loop-persistence", "function"],
  ["jev/no-unbounded-parallel-fanout", "function"],
  ["jev/no-concurrent-shared-mutation", "function"],
  ["jev/no-sensitive-data-in-log", "function"],
  ["jev/no-unsafe-redirect-target", "function"],
  ["jev/no-overbroad-origin-trust", "function"],
  ["jev/no-path-traversal-join", "function"],
  ["jev/no-phantom-member-access", "function"],
  ["jev/no-laundered-absence", "function"],
  ["jev/no-hedging-comment", "comment"],
  ["jev/no-convention-breaking-addition", "function"],
  ["jev/no-repeated-handler-preamble", "function"],
  ["jev/no-non-narrowing-guard", "function"],
  ["jev/no-excess-context-parameter", "function"],
  ["jev/no-shallow-convenience-layer", "function"],
  ["jev/no-prototype-in-production", "function"],
  ["jev/no-hidden-loop-exit", "function"],
] as const;

describe("extracted review rules", () => {
  it.each(extractedRules)("ships %s as a %s judgment", (ruleId, scope) => {
    expect(defaultConfig.rules[ruleId]).toMatchObject({
      scope,
      message: expect.any(String),
    });
    expect(defaultConfig.rules[ruleId]).not.toHaveProperty("threshold");
    expect(defaultConfig.rules[ruleId]).not.toHaveProperty("severity");
  });
});
