export { analyzeChanges, analyzeFile } from "./analyze.js";
export { CachedEvaluator } from "./cache.js";
export type { CacheMode, CacheStatistics, CachedEvaluatorOptions, EvaluatorIdentity } from "./cache.js";
export { extractCandidates, filterCandidatesByChangedLines } from "./candidates.js";
export { parseChangedLineRanges } from "./changed-lines.js";
export { defaultConfig, defineConfig, loadConfig } from "./config.js";
export { deduplicateDiagnostics } from "./deduplicate.js";
export { formatJson, formatText } from "./format.js";
export { collectChangedFiles, collectRepositoryFiles, repositoryCacheContext } from "./git.js";
export { buildAdHocBranchingEvidence } from "./evidence/ad-hoc-branching.js";
export { buildAvoidableOrchestrationEvidence } from "./evidence/avoidable-orchestration.js";
export { buildComplexityDisplacementEvidence } from "./evidence/complexity-displacement.js";
export { buildConditionallyValidStateEvidence } from "./evidence/conditionally-valid-state.js";
export { buildCorrelatedStateBooleansEvidence } from "./evidence/correlated-state-booleans.js";
export { buildDataClumpEvidence } from "./evidence/data-clump.js";
export { buildDisproportionateConfigurationEvidence } from "./evidence/disproportionate-configuration.js";
export { buildDomainPolicyInAdapterEvidence } from "./evidence/domain-policy-in-adapter.js";
export { buildGenericMagicEvidence } from "./evidence/generic-magic.js";
export { buildHiddenInputMutationEvidence } from "./evidence/hidden-input-mutation.js";
export { buildHiddenIoEvidence } from "./evidence/hidden-io.js";
export { buildHiddenPartialFailureEvidence } from "./evidence/hidden-partial-failure.js";
export { buildHiddenInitializationOrderEvidence } from "./evidence/hidden-initialization-order.js";
export { buildHiddenRuntimeInputEvidence } from "./evidence/hidden-runtime-input.js";
export { buildImplicitAtomicityEvidence } from "./evidence/implicit-atomicity.js";
export { buildInterchangeableDomainPrimitivesEvidence } from "./evidence/interchangeable-domain-primitives.js";
export { buildLossyErrorTranslationEvidence } from "./evidence/lossy-error-translation.js";
export { buildLossySentinelReturnEvidence } from "./evidence/lossy-sentinel-return.js";
export { buildMixedResponsibilitiesEvidence } from "./evidence/mixed-responsibilities.js";
export { buildNeedlessAbstractionEvidence } from "./evidence/needless-abstraction.js";
export { buildPassThroughWrapperEvidence } from "./evidence/pass-through-wrapper.js";
export { buildPersistenceModelLeakEvidence } from "./evidence/persistence-model-leak.js";
export { buildQuerySideEffectEvidence } from "./evidence/query-side-effect.js";
export { buildScatteredPolicyEvidence } from "./evidence/scattered-policy.js";
export { buildSpeculativeGeneralityEvidence } from "./evidence/speculative-generality.js";
export { buildSwallowedErrorEvidence } from "./evidence/swallowed-error.js";
export { buildTransportCoupledDomainEvidence } from "./evidence/transport-coupled-domain.js";
export { buildUnconstrainedStateStringEvidence } from "./evidence/unconstrained-state-string.js";
export { buildUnsafeRetryEvidence } from "./evidence/unsafe-retry.js";
export { TypeSafeEvaluator } from "./typesafe-evaluator.js";
export type * from "./types.js";
