// GENERATED by tools/generate-registry.mjs (run `pnpm generate:registry`).
// Do not hand-edit: entries self-register from src/evidence/<kebab>.ts files
// (one exported build*Evidence builder each) joined against src/defaults.ts.
import type { JsonValue } from "@typesafe-ai/sdk";
import type { Candidate, ProjectFile, SourceFile } from "../types.js";
import { buildAccidentalSerializationEvidence } from "./accidental-serialization.js";
import { buildAdHocBranchingEvidence } from "./ad-hoc-branching.js";
import { buildAdversarialRegexEvidence } from "./adversarial-regex.js";
import { buildAmbientDependencyGrabEvidence } from "./ambient-dependency-grab.js";
import { buildAmbiguousPositionalSiblingsEvidence } from "./ambiguous-positional-siblings.js";
import { buildAnemicTypeEvidence } from "./anemic-type.js";
import { buildAssertionFreeTestEvidence } from "./assertion-free-test.js";
import { buildAsymmetricNormalizationEvidence } from "./asymmetric-normalization.js";
import { buildAvoidableOrchestrationEvidence } from "./avoidable-orchestration.js";
import { buildBarrelBypassEvidence } from "./barrel-bypass.js";
import { buildBarrelWideReexportEvidence } from "./barrel-wide-reexport.js";
import { buildBespokeCryptoConstructionEvidence } from "./bespoke-crypto-construction.js";
import { buildBlockingEventLoopCallEvidence } from "./blocking-event-loop-call.js";
import { buildBooleanFanoutEvidence } from "./boolean-fanout.js";
import { buildBreakingExportEvidence } from "./breaking-export-reshape.js";
import { buildCallInLoopPersistenceEvidence } from "./call-in-loop-persistence.js";
import { buildCallbackReturnSplitEvidence } from "./callback-return-split.js";
import { buildCascadingFallbackEvidence } from "./cascading-fallback.js";
import { buildChangeAmplifierCaseEvidence } from "./change-amplifier-case.js";
import { buildChangeStrandedCodeEvidence } from "./change-stranded-code.js";
import { buildChattyInterfaceEvidence } from "./chatty-interface.js";
import { buildCheckThenActRaceEvidence } from "./check-then-act-race.js";
import { buildCleverExpressionEvidence } from "./clever-expression.js";
import { buildClientOnlyAuthorizationEvidence } from "./client-only-authorization.js";
import { buildCloneAndTweakSiblingEvidence } from "./clone-and-tweak-sibling.js";
import { buildCoincidentalSimilarityEvidence } from "./coincidental-similarity.js";
import { buildCommentedOutImplementationEvidence } from "./commented-out-implementation.js";
import { buildComplexityDisplacementEvidence } from "./complexity-displacement.js";
import { buildConcreteStableModuleEvidence } from "./concrete-stable-module.js";
import { buildConcurrentSharedMutationEvidence } from "./concurrent-shared-mutation.js";
import { buildConditionallyValidStateEvidence } from "./conditionally-valid-state.js";
import { buildConfusionConfessingCommentEvidence } from "./confusion-confessing-comment.js";
import { buildConsoleResidueEvidence } from "./console-residue.js";
import { buildConstructionInUseEvidence } from "./construction-in-use.js";
import { buildContextHomonymTypeEvidence } from "./context-homonym-type.js";
import { buildContextlessErrorEvidence } from "./contextless-error.js";
import { buildContractNarrowingEvidence } from "./contract-narrowing-after-ship.js";
import { buildContractSignatureDriftEvidence } from "./contract-signature-drift.js";
import { buildConventionBreakingAdditionEvidence } from "./convention-breaking-addition.js";
import { buildConvergentTwinTypesEvidence } from "./convergent-twin-types.js";
import { buildCorrelatedStateBooleansEvidence } from "./correlated-state-booleans.js";
import { buildCrossAreaExportBreakEvidence } from "./cross-area-export-break.js";
import { buildCrossContextTestReachEvidence } from "./cross-context-test-reach.js";
import { buildCrossModuleCallOrderEvidence } from "./cross-module-call-order.js";
import { buildCrossServiceSourceReachEvidence } from "./cross-service-source-reach.js";
import { buildCrypticAbbreviationEvidence } from "./cryptic-abbreviation.js";
import { buildDataClumpEvidence } from "./data-clump.js";
import { buildDeceptiveNameEvidence } from "./deceptive-name.js";
import { buildDeepDelegationChainEvidence } from "./deep-delegation-chain.js";
import { buildDeepHappyPathNestingEvidence } from "./deep-happy-path-nesting.js";
import { buildDeploymentCoupledAssumptionEvidence } from "./deployment-coupled-assumption.js";
import { buildDetachedAsyncWorkEvidence } from "./detached-async-work.js";
import { buildDevDependencyRuntimeLeakEvidence } from "./dev-dependency-runtime-leak.js";
import { buildDirectionReversingEdgeEvidence } from "./direction-reversing-edge.js";
import { buildDisabledTlsVerificationEvidence } from "./disabled-tls-verification.js";
import { buildDiscardedTransformationEvidence } from "./discarded-transformation.js";
import { buildDisproportionateConfigurationEvidence } from "./disproportionate-configuration.js";
import { buildDistrustfulTypeGuardEvidence } from "./distrustful-type-guard.js";
import { buildDivergentChangeEvidence } from "./divergent-change.js";
import { buildDivergentInversesEvidence } from "./divergent-inverses.js";
import { buildDivergentSiblingInterfacesEvidence } from "./divergent-sibling-interfaces.js";
import { buildDomainPolicyInAdapterEvidence } from "./domain-policy-in-adapter.js";
import { buildDomainUpwardImportEvidence } from "./domain-upward-import.js";
import { buildDoubleNegationEvidence } from "./double-negation.js";
import { buildDoubledPureHelperEvidence } from "./doubled-pure-helper.js";
import { buildDrilledPropEvidence } from "./drilled-prop.js";
import { buildDuplicateConfigSourceEvidence } from "./duplicate-config-source.js";
import { buildDuplicateModuleRoleEvidence } from "./duplicate-module-role.js";
import { buildDuplicatedFixtureDriftEvidence } from "./duplicated-fixture-drift.js";
import { buildDuplicatedLogicEvidence } from "./duplicated-logic.js";
import { buildDuplicatedStyleObjectEvidence } from "./duplicated-style-object.js";
import { buildDynamicCodeExecutionEvidence } from "./dynamic-code-execution.js";
import { buildEfferentCouplingBurstEvidence } from "./efferent-coupling-burst.js";
import { buildEnglishOnlyPluralizationEvidence } from "./english-only-pluralization.js";
import { buildEntangledMechanicalChangeEvidence } from "./entangled-mechanical-change.js";
import { buildExcessContextParameterEvidence } from "./excess-context-parameter.js";
import { buildFalsyAbsentConflationEvidence } from "./falsy-absent-conflation.js";
import { buildFarAwayTestEvidence } from "./far-away-test.js";
import { buildFlagShepherdedControlFlowEvidence } from "./flag-shepherded-control-flow.js";
import { buildFlakyOrderAssertionEvidence } from "./flaky-order-assertion.js";
import { buildFloatingMoneyArithmeticEvidence } from "./floating-money-arithmetic.js";
import { buildForeignMutationEvidence } from "./foreign-mutation.js";
import { buildFragmentedStatefulProcedureEvidence } from "./fragmented-stateful-procedure.js";
import { buildFsRecursiveReinventEvidence } from "./fs-recursive-reinvent.js";
import { buildGenericMagicEvidence } from "./generic-magic.js";
import { buildGiantTestArrangeEvidence } from "./giant-test-arrange.js";
import { buildHandRolledConcurrencyLimitEvidence } from "./hand-rolled-concurrency-limit.js";
import { buildHandRolledCsvSplitEvidence } from "./hand-rolled-csv-split.js";
import { buildHandRolledDateFormatEvidence } from "./hand-rolled-date-format.js";
import { buildHandRolledDebounceEvidence } from "./hand-rolled-debounce.js";
import { buildHandRolledDeepCloneEvidence } from "./hand-rolled-deep-clone.js";
import { buildHandRolledDeepEqualEvidence } from "./hand-rolled-deep-equal.js";
import { buildHandRolledEventBusEvidence } from "./hand-rolled-event-bus.js";
import { buildHandRolledFetchWrapperEvidence } from "./hand-rolled-fetch-wrapper.js";
import { buildHandRolledFlattenEvidence } from "./hand-rolled-flatten.js";
import { buildHandRolledGroupByEvidence } from "./hand-rolled-group-by.js";
import { buildHandRolledNumberFormatEvidence } from "./hand-rolled-number-format.js";
import { buildHandRolledPromiseTimeoutEvidence } from "./hand-rolled-promise-timeout.js";
import { buildHandRolledRelativeTimeEvidence } from "./hand-rolled-relative-time.js";
import { buildHandRolledRetryLoopEvidence } from "./hand-rolled-retry-loop.js";
import { buildHandRolledSchemaCheckEvidence } from "./hand-rolled-schema-check.js";
import { buildHandRolledSetOpsEvidence } from "./hand-rolled-set-ops.js";
import { buildHandRolledStringHashEvidence } from "./hand-rolled-string-hash.js";
import { buildHandRolledUrlQueryEvidence } from "./hand-rolled-url-query.js";
import { buildHandRolledUuidEvidence } from "./hand-rolled-uuid.js";
import { buildHardcodedConfigShadowEvidence } from "./hardcoded-config-shadow.js";
import { buildHeterogeneousPrimitiveCallersEvidence } from "./heterogeneous-primitive-callers.js";
import { buildHiddenCollaboratorReadEvidence } from "./hidden-collaborator-read.js";
import { buildHiddenInitializationOrderEvidence } from "./hidden-initialization-order.js";
import { buildHiddenInputMutationEvidence } from "./hidden-input-mutation.js";
import { buildHiddenIoEvidence } from "./hidden-io.js";
import { buildHiddenLoopExitEvidence } from "./hidden-loop-exit.js";
import { buildHiddenPartialFailureEvidence } from "./hidden-partial-failure.js";
import { buildHiddenRuntimeInputEvidence } from "./hidden-runtime-input.js";
import { buildHollowDelegationChainEvidence } from "./hollow-delegation-chain.js";
import { buildImplementationMirroredExpectationEvidence } from "./implementation-mirrored-expectation.js";
import { buildImplementationTypeInSignatureEvidence } from "./implementation-type-in-signature.js";
import { buildImplicitAtomicityEvidence } from "./implicit-atomicity.js";
import { buildImportCycleTangleEvidence } from "./import-cycle-tangle.js";
import { buildImportUseSkewEvidence } from "./import-use-skew.js";
import { buildImpossibleErrorBranchEvidence } from "./impossible-error-branch.js";
import { buildInappropriateIntimacyEvidence } from "./inappropriate-intimacy.js";
import { buildIncidentalSnapshotEvidence } from "./incidental-snapshot.js";
import { buildInconsistentErrorContractEvidence } from "./inconsistent-error-contract.js";
import { buildInlineLifecyclePhasesEvidence } from "./inline-lifecycle-phases.js";
import { buildInteractionPinningTestEvidence } from "./interaction-pinning-test.js";
import { buildInterchangeableDomainPrimitivesEvidence } from "./interchangeable-domain-primitives.js";
import { buildInvertedAuthorizationPredicateEvidence } from "./inverted-authorization-predicate.js";
import { buildKnobMultiplicityEvidence } from "./knob-multiplicity.js";
import { buildLaunderedAbsenceEvidence } from "./laundered-absence.js";
import { buildLayerSkippingCallEvidence } from "./layer-skipping-call.js";
import { buildLeakyInternalExportEvidence } from "./leaky-internal-export.js";
import { buildLiveCredentialEvidence } from "./live-credential.js";
import { buildLoadBearingAsyncEvidence } from "./load-bearing-async.js";
import { buildLocaleBlindOrderingEvidence } from "./locale-blind-ordering.js";
import { buildLocaleDateSerializationEvidence } from "./locale-date-serialization.js";
import { buildLogicInTestEvidence } from "./logic-in-test.js";
import { buildLopsidedErrorHandlingEvidence } from "./lopsided-error-handling.js";
import { buildLossyErrorTranslationEvidence } from "./lossy-error-translation.js";
import { buildLossySentinelReturnEvidence } from "./lossy-sentinel-return.js";
import { buildLowCohesionClassEvidence } from "./low-cohesion-class.js";
import { buildMessageChainEvidence } from "./message-chain.js";
import { buildMirroredDerivedStateEvidence } from "./mirrored-derived-state.js";
import { buildMisdirectingErrorMessageEvidence } from "./misdirecting-error-message.js";
import { buildMisplacedCoordinationEvidence } from "./misplaced-coordination.js";
import { buildMisplacedErrorBoundaryEvidence } from "./misplaced-error-boundary.js";
import { buildMissingHealthSignalEvidence } from "./missing-health-signal.js";
import { buildMissingShutdownDrainEvidence } from "./missing-shutdown-drain.js";
import { buildMixedAbsenceConventionEvidence } from "./mixed-absence-convention.js";
import { buildMixedAbstractionLevelsEvidence } from "./mixed-abstraction-levels.js";
import { buildMixedCalculationAndInteractionEvidence } from "./mixed-calculation-and-interaction.js";
import { buildMixedResponsibilitiesEvidence } from "./mixed-responsibilities.js";
import { buildMockEverythingEvidence } from "./mock-everything.js";
import { buildModeFlagParameterEvidence } from "./mode-flag-parameter.js";
import { buildMutableSurfaceExpansionEvidence } from "./mutable-surface-expansion.js";
import { buildMysteriousNameEvidence } from "./mysterious-name.js";
import { buildMysteryLiteralArgumentEvidence } from "./mystery-literal-argument.js";
import { buildNeedlessAbstractionEvidence } from "./needless-abstraction.js";
import { buildNegativeBooleanNameEvidence } from "./negative-boolean-name.js";
import { buildNestedConditionalExpressionEvidence } from "./nested-conditional-expression.js";
import { buildNewForeignStateWriteEdgeEvidence } from "./new-foreign-state-write-edge.js";
import { buildNonExhaustiveDomainHandlingEvidence } from "./non-exhaustive-domain-handling.js";
import { buildNonIdempotentRetryEvidence } from "./non-idempotent-retry.js";
import { buildNonNarrowingGuardEvidence } from "./non-narrowing-guard.js";
import { buildNondeterministicTestInputEvidence } from "./nondeterministic-test-input.js";
import { buildOffsetPaginationDriftEvidence } from "./offset-pagination-drift.js";
import { buildOptionsStyleSplitEvidence } from "./options-style-split.js";
import { buildOrphanedTimerEvidence } from "./orphaned-timer.js";
import { buildOutputArgumentEvidence } from "./output-argument.js";
import { buildOverbroadOriginTrustEvidence } from "./overbroad-origin-trust.js";
import { buildOverloadResolutionAmbiguityEvidence } from "./overload-resolution-ambiguity.js";
import { buildOverloadedBooleanReturnEvidence } from "./overloaded-boolean-return.js";
import { buildOversizedWorkingSetEvidence } from "./oversized-working-set.js";
import { buildParallelAbstractionEvidence } from "./parallel-abstraction.js";
import { buildParallelEnumerationsEvidence } from "./parallel-enumerations.js";
import { buildParaphrasedSiblingLogicEvidence } from "./paraphrased-sibling-logic.js";
import { buildPartiallyNarrowedNullableEvidence } from "./partially-narrowed-nullable.js";
import { buildPartitionedFatInterfaceEvidence } from "./partitioned-fat-interface.js";
import { buildPassThroughWrapperEvidence } from "./pass-through-wrapper.js";
import { buildPathTraversalJoinEvidence } from "./path-traversal-join.js";
import { buildPersistenceModelLeakEvidence } from "./persistence-model-leak.js";
import { buildPhantomMemberAccessEvidence } from "./phantom-member-access.js";
import { buildPhantomPackageImportEvidence } from "./phantom-package-import.js";
import { buildPositionalExtensionDriftEvidence } from "./positional-extension-drift.js";
import { buildPreGateSideEffectEvidence } from "./pre-gate-side-effect.js";
import { buildPredicateNameDeceptionEvidence } from "./predicate-name-deception.js";
import { buildPredictableTokenEvidence } from "./predictable-token.js";
import { buildPrivateInternalsAssertionEvidence } from "./private-internals-assertion.js";
import { buildPromiseCombinatorMismatchEvidence } from "./promise-combinator-mismatch.js";
import { buildPrototypeInProductionEvidence } from "./prototype-in-production.js";
import { buildPunnedNameEvidence } from "./punned-name.js";
import { buildQuarantinedTestCoverageEvidence } from "./quarantined-test-coverage.js";
import { buildQuerySideEffectEvidence } from "./query-side-effect.js";
import { buildRareCaseFirstEvidence } from "./rare-case-first.js";
import { buildRedundantConditionalArmEvidence } from "./redundant-conditional-arm.js";
import { buildReentrantEntryEvidence } from "./reentrant-entry.js";
import { buildRefusedInheritanceEvidence } from "./refused-inheritance.js";
import { buildRepeatedHandlerPreambleEvidence } from "./repeated-handler-preamble.js";
import { buildRepeatedPredicateEvidence } from "./repeated-predicate.js";
import { buildRepeatedTestPreambleEvidence } from "./repeated-test-preamble.js";
import { buildRetainedSupersededImplementationEvidence } from "./retained-superseded-implementation.js";
import { buildRetryStormEvidence } from "./retry-storm-shape.js";
import { buildSameStemDivergentRoleEvidence } from "./same-stem-divergent-role.js";
import { buildScatteredPolicyEvidence } from "./scattered-policy.js";
import { buildSecondShelfDependencyEvidence } from "./second-shelf-dependency.js";
import { buildSelfAuthoredExamEvidence } from "./self-authored-exam.js";
import { buildSensitiveDataInLogEvidence } from "./sensitive-data-in-log.js";
import { buildSequentialStepSoupEvidence } from "./sequential-step-soup.js";
import { buildShadowedMeaningEvidence } from "./shadowed-meaning.js";
import { buildShallowConvenienceLayerEvidence } from "./shallow-convenience-layer.js";
import { buildSharedKernelNewConsumerEvidence } from "./shared-kernel-new-consumer.js";
import { buildSharedMutableDefaultEvidence } from "./shared-mutable-default.js";
import { buildSharedMutableModuleStateEvidence } from "./shared-mutable-module-state.js";
import { buildShotgunChangeEvidence } from "./shotgun-change.js";
import { buildSiblingIdentifierSwapEvidence } from "./sibling-identifier-swap.js";
import { buildSideEffectingConditionalEvidence } from "./side-effecting-conditional-expression.js";
import { buildSilentQueueDropEvidence } from "./silent-queue-drop.js";
import { buildSingleCallerExportedHelperEvidence } from "./single-caller-exported-helper.js";
import { buildSingleUseDependencyEvidence } from "./single-use-dependency.js";
import { buildSinglyOwnedLazySharedStateEvidence } from "./singly-owned-lazy-shared-state.js";
import { buildSkippedLevelImportEvidence } from "./skipped-level-import.js";
import { buildSleepInTestEvidence } from "./sleep-in-test.js";
import { buildSpeculativeGeneralityEvidence } from "./speculative-generality.js";
import { buildStabilityInversionEvidence } from "./stability-inversion.js";
import { buildStableSurfaceWideningEvidence } from "./stable-surface-widening.js";
import { buildStableToVolatileEdgeEvidence } from "./stable-to-volatile-edge.js";
import { buildStaleBindingUseEvidence } from "./stale-binding-use.js";
import { buildStaleCommentEvidence } from "./stale-comment.js";
import { buildStaleFeatureFlagEvidence } from "./stale-feature-flag.js";
import { buildStringDuplicatedEnumerationEvidence } from "./string-duplicated-enumeration.js";
import { buildSubclassFragilityHookEvidence } from "./subclass-fragility-hook.js";
import { buildSupersededApiUseEvidence } from "./superseded-api-use.js";
import { buildSwallowedErrorEvidence } from "./swallowed-error.js";
import { buildSyncAsyncSiblingAmbiguityEvidence } from "./sync-async-sibling-ambiguity.js";
import { buildSynonymVocabularyEvidence } from "./synonym-vocabulary.js";
import { buildTableConditionalEvidence } from "./table-shaped-conditional.js";
import { buildTeamBoundaryCrossingEvidence } from "./team-boundary-crossing.js";
import { buildTemporalCallCouplingEvidence } from "./temporal-call-coupling.js";
import { buildTemporaryFieldEvidence } from "./temporary-field.js";
import { buildTimezoneNaiveArithmeticEvidence } from "./timezone-naive-arithmetic.js";
import { buildTransitivePlumbingEvidence } from "./transitive-plumbing.js";
import { buildTransportCoupledDomainEvidence } from "./transport-coupled-domain.js";
import { buildTruncatingNumericParseEvidence } from "./truncating-numeric-parse.js";
import { buildTwinGatewayEmergenceEvidence } from "./twin-gateway-emergence.js";
import { buildTypeCheckerEscapeEvidence } from "./type-checker-escape.js";
import { buildTypeCodeDispatchEvidence } from "./type-code-dispatch.js";
import { buildUnanchoredDomainCheckEvidence } from "./unanchored-domain-check.js";
import { buildUnawaitedIterationWorkEvidence } from "./unawaited-iteration-work.js";
import { buildUnboundedAccumulationEvidence } from "./unbounded-accumulation.js";
import { buildUnboundedParallelFanoutEvidence } from "./unbounded-parallel-fanout.js";
import { buildUnboundedWaitEvidence } from "./unbounded-wait.js";
import { buildUncheckedPreconditionEvidence } from "./unchecked-precondition.js";
import { buildUnclosedHandleEvidence } from "./unclosed-handle.js";
import { buildUnconstrainedStateStringEvidence } from "./unconstrained-state-string.js";
import { buildUnconsumedTelemetryEvidence } from "./unconsumed-telemetry.js";
import { buildUndocumentedContractEvidence } from "./undocumented-contract.js";
import { buildUnenforcedWarningCommentEvidence } from "./unenforced-warning-comment.js";
import { buildUnexplainedBehavioralLiteralEvidence } from "./unexplained-behavioral-literal.js";
import { buildUnexplainedComplexConditionEvidence } from "./unexplained-complex-condition.js";
import { buildUnexplainedDomainThresholdEvidence } from "./unexplained-domain-threshold.js";
import { buildUnexplainedSuppressionEvidence } from "./unexplained-suppression.js";
import { buildUnguardedAsyncInitEvidence } from "./unguarded-async-init.js";
import { buildUnguardedNullableDereferenceEvidence } from "./unguarded-nullable-dereference.js";
import { buildUnitAmbiguousQuantityEvidence } from "./unit-ambiguous-quantity.js";
import { buildUnitScaleMismatchEvidence } from "./unit-scale-mismatch.js";
import { buildUnitlessQuantityEvidence } from "./unitless-quantity.js";
import { buildUnlabeledInteractiveElementEvidence } from "./unlabeled-interactive-element.js";
import { buildUnlocalizedUserStringEvidence } from "./unlocalized-user-string.js";
import { buildUnmarkedAbandonedCompatLayerEvidence } from "./unmarked-abandoned-compat-layer.js";
import { buildUnmeasuredPerformanceMachineryEvidence } from "./unmeasured-performance-machinery.js";
import { buildUnmigratedSchemaChangeEvidence } from "./unmigrated-schema-change.js";
import { buildUnnamedParameterObjectEvidence } from "./unnamed-parameter-object.js";
import { buildUnownedFeatureFlagEvidence } from "./unowned-feature-flag.js";
import { buildUnpinnedBoundaryBranchEvidence } from "./unpinned-boundary-branch.js";
import { buildUnpinnedCompatQuirkEvidence } from "./unpinned-compat-quirk.js";
import { buildUnpinnedFailurePathEvidence } from "./unpinned-failure-path.js";
import { buildUnreachableGuardEvidence } from "./unreachable-guard.js";
import { buildUnreleasedSubscriptionEvidence } from "./unreleased-subscription.js";
import { buildUnsafeRedirectTargetEvidence } from "./unsafe-redirect-target.js";
import { buildUnsafeRetryEvidence } from "./unsafe-retry.js";
import { buildUnsynchronizedSharedMemoryEvidence } from "./unsynchronized-shared-memory.js";
import { buildUntestableSingletonGrabEvidence } from "./untestable-singleton-grab.js";
import { buildUntrustedSinkInputEvidence } from "./untrusted-sink-input.js";
import { buildUnusedExportedHelperEvidence } from "./unused-exported-helper.js";
import { buildUnvalidatedBoundaryEvidence } from "./unvalidated-boundary-shape.js";
import { buildUnverifiedClaimEvidence } from "./unverified-claim.js";
import { buildUnverifiedMockContractEvidence } from "./unverified-mock-contract.js";
import { buildUnversionedEnvelopeChangeEvidence } from "./unversioned-envelope-change.js";
import { buildUnwieldySignatureEvidence } from "./unwieldy-signature.js";
import { buildUnwrappedServiceEdgeEvidence } from "./unwrapped-service-edge.js";
import { buildUtilityModuleGrabBagEvidence } from "./utility-module-grab-bag.js";
import { buildUtilsGrabBagGrowthEvidence } from "./utils-grab-bag-growth.js";
import { buildVariantPartitionedHelperEvidence } from "./variant-partitioned-helper.js";
import { buildVerblessFunctionNameEvidence } from "./verbless-function-name.js";
import { buildWeakCryptoPrimitiveEvidence } from "./weak-crypto-primitive.js";
import { buildWideFanInEditEvidence } from "./wide-fan-in-edit.js";

export type RuleEvidenceResult =
  | { handled: false }
  | { handled: true; evidence: JsonValue | undefined };

type EvidenceBuilder = (
  candidate: Candidate,
  projectFiles: ProjectFile[],
  changes: SourceFile[],
) => JsonValue | undefined;

type EvidenceRegistry = {
  "jev/no-accidental-serialization": EvidenceBuilder;
  "jev/no-ad-hoc-branching": EvidenceBuilder;
  "jev/no-adversarial-regex": EvidenceBuilder;
  "jev/no-ambient-dependency-grab": EvidenceBuilder;
  "jev/no-ambiguous-positional-siblings": EvidenceBuilder;
  "jev/no-anemic-type": EvidenceBuilder;
  "jev/no-assertion-free-test": EvidenceBuilder;
  "jev/no-asymmetric-normalization": EvidenceBuilder;
  "jev/no-avoidable-orchestration": EvidenceBuilder;
  "jev/no-barrel-bypass": EvidenceBuilder;
  "jev/no-barrel-wide-reexport": EvidenceBuilder;
  "jev/no-bespoke-crypto-construction": EvidenceBuilder;
  "jev/no-blocking-event-loop-call": EvidenceBuilder;
  "jev/no-boolean-fanout": EvidenceBuilder;
  "jev/no-breaking-export-reshape": EvidenceBuilder;
  "jev/no-call-in-loop-persistence": EvidenceBuilder;
  "jev/no-callback-return-split": EvidenceBuilder;
  "jev/no-cascading-fallback": EvidenceBuilder;
  "jev/no-change-amplifier-case": EvidenceBuilder;
  "jev/no-change-stranded-code": EvidenceBuilder;
  "jev/no-chatty-interface": EvidenceBuilder;
  "jev/no-check-then-act-race": EvidenceBuilder;
  "jev/no-clever-expression": EvidenceBuilder;
  "jev/no-client-only-authorization": EvidenceBuilder;
  "jev/no-clone-and-tweak-sibling": EvidenceBuilder;
  "jev/no-coincidental-similarity": EvidenceBuilder;
  "jev/no-commented-out-implementation": EvidenceBuilder;
  "jev/no-complexity-displacement": EvidenceBuilder;
  "jev/no-concrete-stable-module": EvidenceBuilder;
  "jev/no-concurrent-shared-mutation": EvidenceBuilder;
  "jev/no-conditionally-valid-state": EvidenceBuilder;
  "jev/no-confusion-confessing-comment": EvidenceBuilder;
  "jev/no-console-residue": EvidenceBuilder;
  "jev/no-construction-in-use": EvidenceBuilder;
  "jev/no-context-homonym-type": EvidenceBuilder;
  "jev/no-contextless-error": EvidenceBuilder;
  "jev/no-contract-narrowing-after-ship": EvidenceBuilder;
  "jev/no-contract-signature-drift": EvidenceBuilder;
  "jev/no-convention-breaking-addition": EvidenceBuilder;
  "jev/no-convergent-twin-types": EvidenceBuilder;
  "jev/no-correlated-state-booleans": EvidenceBuilder;
  "jev/no-cross-area-export-break": EvidenceBuilder;
  "jev/no-cross-context-test-reach": EvidenceBuilder;
  "jev/no-cross-module-call-order": EvidenceBuilder;
  "jev/no-cross-service-source-reach": EvidenceBuilder;
  "jev/no-cryptic-abbreviation": EvidenceBuilder;
  "jev/no-data-clump": EvidenceBuilder;
  "jev/no-deceptive-name": EvidenceBuilder;
  "jev/no-deep-delegation-chain": EvidenceBuilder;
  "jev/no-deep-happy-path-nesting": EvidenceBuilder;
  "jev/no-deployment-coupled-assumption": EvidenceBuilder;
  "jev/no-detached-async-work": EvidenceBuilder;
  "jev/no-dev-dependency-runtime-leak": EvidenceBuilder;
  "jev/no-direction-reversing-edge": EvidenceBuilder;
  "jev/no-disabled-tls-verification": EvidenceBuilder;
  "jev/no-discarded-transformation": EvidenceBuilder;
  "jev/no-disproportionate-configuration": EvidenceBuilder;
  "jev/no-distrustful-type-guard": EvidenceBuilder;
  "jev/no-divergent-change": EvidenceBuilder;
  "jev/no-divergent-inverses": EvidenceBuilder;
  "jev/no-divergent-sibling-interfaces": EvidenceBuilder;
  "jev/no-domain-policy-in-adapter": EvidenceBuilder;
  "jev/no-domain-upward-import": EvidenceBuilder;
  "jev/no-double-negation": EvidenceBuilder;
  "jev/no-doubled-pure-helper": EvidenceBuilder;
  "jev/no-drilled-prop": EvidenceBuilder;
  "jev/no-duplicate-config-source": EvidenceBuilder;
  "jev/no-duplicate-module-role": EvidenceBuilder;
  "jev/no-duplicated-fixture-drift": EvidenceBuilder;
  "jev/no-duplicated-logic": EvidenceBuilder;
  "jev/no-duplicated-style-object": EvidenceBuilder;
  "jev/no-dynamic-code-execution": EvidenceBuilder;
  "jev/no-efferent-coupling-burst": EvidenceBuilder;
  "jev/no-english-only-pluralization": EvidenceBuilder;
  "jev/no-entangled-mechanical-change": EvidenceBuilder;
  "jev/no-excess-context-parameter": EvidenceBuilder;
  "jev/no-falsy-absent-conflation": EvidenceBuilder;
  "jev/no-far-away-test": EvidenceBuilder;
  "jev/no-flag-shepherded-control-flow": EvidenceBuilder;
  "jev/no-flaky-order-assertion": EvidenceBuilder;
  "jev/no-floating-money-arithmetic": EvidenceBuilder;
  "jev/no-foreign-mutation": EvidenceBuilder;
  "jev/no-fragmented-stateful-procedure": EvidenceBuilder;
  "jev/no-fs-recursive-reinvent": EvidenceBuilder;
  "jev/no-generic-magic": EvidenceBuilder;
  "jev/no-giant-test-arrange": EvidenceBuilder;
  "jev/no-hand-rolled-concurrency-limit": EvidenceBuilder;
  "jev/no-hand-rolled-csv-split": EvidenceBuilder;
  "jev/no-hand-rolled-date-format": EvidenceBuilder;
  "jev/no-hand-rolled-debounce": EvidenceBuilder;
  "jev/no-hand-rolled-deep-clone": EvidenceBuilder;
  "jev/no-hand-rolled-deep-equal": EvidenceBuilder;
  "jev/no-hand-rolled-event-bus": EvidenceBuilder;
  "jev/no-hand-rolled-fetch-wrapper": EvidenceBuilder;
  "jev/no-hand-rolled-flatten": EvidenceBuilder;
  "jev/no-hand-rolled-group-by": EvidenceBuilder;
  "jev/no-hand-rolled-number-format": EvidenceBuilder;
  "jev/no-hand-rolled-promise-timeout": EvidenceBuilder;
  "jev/no-hand-rolled-relative-time": EvidenceBuilder;
  "jev/no-hand-rolled-retry-loop": EvidenceBuilder;
  "jev/no-hand-rolled-schema-check": EvidenceBuilder;
  "jev/no-hand-rolled-set-ops": EvidenceBuilder;
  "jev/no-hand-rolled-string-hash": EvidenceBuilder;
  "jev/no-hand-rolled-url-query": EvidenceBuilder;
  "jev/no-hand-rolled-uuid": EvidenceBuilder;
  "jev/no-hardcoded-config-shadow": EvidenceBuilder;
  "jev/no-heterogeneous-primitive-callers": EvidenceBuilder;
  "jev/no-hidden-collaborator-read": EvidenceBuilder;
  "jev/no-hidden-initialization-order": EvidenceBuilder;
  "jev/no-hidden-input-mutation": EvidenceBuilder;
  "jev/no-hidden-io": EvidenceBuilder;
  "jev/no-hidden-loop-exit": EvidenceBuilder;
  "jev/no-hidden-partial-failure": EvidenceBuilder;
  "jev/no-hidden-runtime-input": EvidenceBuilder;
  "jev/no-hollow-delegation-chain": EvidenceBuilder;
  "jev/no-implementation-mirrored-expectation": EvidenceBuilder;
  "jev/no-implementation-type-in-signature": EvidenceBuilder;
  "jev/no-implicit-atomicity": EvidenceBuilder;
  "jev/no-import-cycle-tangle": EvidenceBuilder;
  "jev/no-import-use-skew": EvidenceBuilder;
  "jev/no-impossible-error-branch": EvidenceBuilder;
  "jev/no-inappropriate-intimacy": EvidenceBuilder;
  "jev/no-incidental-snapshot": EvidenceBuilder;
  "jev/no-inconsistent-error-contract": EvidenceBuilder;
  "jev/no-inline-lifecycle-phases": EvidenceBuilder;
  "jev/no-interaction-pinning-test": EvidenceBuilder;
  "jev/no-interchangeable-domain-primitives": EvidenceBuilder;
  "jev/no-inverted-authorization-predicate": EvidenceBuilder;
  "jev/no-knob-multiplicity": EvidenceBuilder;
  "jev/no-laundered-absence": EvidenceBuilder;
  "jev/no-layer-skipping-call": EvidenceBuilder;
  "jev/no-leaky-internal-export": EvidenceBuilder;
  "jev/no-live-credential": EvidenceBuilder;
  "jev/no-load-bearing-async": EvidenceBuilder;
  "jev/no-locale-blind-ordering": EvidenceBuilder;
  "jev/no-locale-date-serialization": EvidenceBuilder;
  "jev/no-logic-in-test": EvidenceBuilder;
  "jev/no-lopsided-error-handling": EvidenceBuilder;
  "jev/no-lossy-error-translation": EvidenceBuilder;
  "jev/no-lossy-sentinel-return": EvidenceBuilder;
  "jev/no-low-cohesion-class": EvidenceBuilder;
  "jev/no-message-chain": EvidenceBuilder;
  "jev/no-mirrored-derived-state": EvidenceBuilder;
  "jev/no-misdirecting-error-message": EvidenceBuilder;
  "jev/no-misplaced-coordination": EvidenceBuilder;
  "jev/no-misplaced-error-boundary": EvidenceBuilder;
  "jev/no-missing-health-signal": EvidenceBuilder;
  "jev/no-missing-shutdown-drain": EvidenceBuilder;
  "jev/no-mixed-absence-convention": EvidenceBuilder;
  "jev/no-mixed-abstraction-levels": EvidenceBuilder;
  "jev/no-mixed-calculation-and-interaction": EvidenceBuilder;
  "jev/no-mixed-responsibilities": EvidenceBuilder;
  "jev/no-mock-everything": EvidenceBuilder;
  "jev/no-mode-flag-parameter": EvidenceBuilder;
  "jev/no-mutable-surface-expansion": EvidenceBuilder;
  "jev/no-mysterious-name": EvidenceBuilder;
  "jev/no-mystery-literal-argument": EvidenceBuilder;
  "jev/no-needless-abstraction": EvidenceBuilder;
  "jev/no-negative-boolean-name": EvidenceBuilder;
  "jev/no-nested-conditional-expression": EvidenceBuilder;
  "jev/no-new-foreign-state-write-edge": EvidenceBuilder;
  "jev/no-non-exhaustive-domain-handling": EvidenceBuilder;
  "jev/no-non-idempotent-retry": EvidenceBuilder;
  "jev/no-non-narrowing-guard": EvidenceBuilder;
  "jev/no-nondeterministic-test-input": EvidenceBuilder;
  "jev/no-offset-pagination-drift": EvidenceBuilder;
  "jev/no-options-style-split": EvidenceBuilder;
  "jev/no-orphaned-timer": EvidenceBuilder;
  "jev/no-output-argument": EvidenceBuilder;
  "jev/no-overbroad-origin-trust": EvidenceBuilder;
  "jev/no-overload-resolution-ambiguity": EvidenceBuilder;
  "jev/no-overloaded-boolean-return": EvidenceBuilder;
  "jev/no-oversized-working-set": EvidenceBuilder;
  "jev/no-parallel-abstraction": EvidenceBuilder;
  "jev/no-parallel-enumerations": EvidenceBuilder;
  "jev/no-paraphrased-sibling-logic": EvidenceBuilder;
  "jev/no-partially-narrowed-nullable": EvidenceBuilder;
  "jev/no-partitioned-fat-interface": EvidenceBuilder;
  "jev/no-pass-through-wrapper": EvidenceBuilder;
  "jev/no-path-traversal-join": EvidenceBuilder;
  "jev/no-persistence-model-leak": EvidenceBuilder;
  "jev/no-phantom-member-access": EvidenceBuilder;
  "jev/no-phantom-package-import": EvidenceBuilder;
  "jev/no-positional-extension-drift": EvidenceBuilder;
  "jev/no-pre-gate-side-effect": EvidenceBuilder;
  "jev/no-predicate-name-deception": EvidenceBuilder;
  "jev/no-predictable-token": EvidenceBuilder;
  "jev/no-private-internals-assertion": EvidenceBuilder;
  "jev/no-promise-combinator-mismatch": EvidenceBuilder;
  "jev/no-prototype-in-production": EvidenceBuilder;
  "jev/no-punned-name": EvidenceBuilder;
  "jev/no-quarantined-test-coverage": EvidenceBuilder;
  "jev/no-query-side-effect": EvidenceBuilder;
  "jev/no-rare-case-first": EvidenceBuilder;
  "jev/no-redundant-conditional-arm": EvidenceBuilder;
  "jev/no-reentrant-entry": EvidenceBuilder;
  "jev/no-refused-inheritance": EvidenceBuilder;
  "jev/no-repeated-handler-preamble": EvidenceBuilder;
  "jev/no-repeated-predicate": EvidenceBuilder;
  "jev/no-repeated-test-preamble": EvidenceBuilder;
  "jev/no-retained-superseded-implementation": EvidenceBuilder;
  "jev/no-retry-storm-shape": EvidenceBuilder;
  "jev/no-same-stem-divergent-role": EvidenceBuilder;
  "jev/no-scattered-policy": EvidenceBuilder;
  "jev/no-second-shelf-dependency": EvidenceBuilder;
  "jev/no-self-authored-exam": EvidenceBuilder;
  "jev/no-sensitive-data-in-log": EvidenceBuilder;
  "jev/no-sequential-step-soup": EvidenceBuilder;
  "jev/no-shadowed-meaning": EvidenceBuilder;
  "jev/no-shallow-convenience-layer": EvidenceBuilder;
  "jev/no-shared-kernel-new-consumer": EvidenceBuilder;
  "jev/no-shared-mutable-default": EvidenceBuilder;
  "jev/no-shared-mutable-module-state": EvidenceBuilder;
  "jev/no-shotgun-change": EvidenceBuilder;
  "jev/no-sibling-identifier-swap": EvidenceBuilder;
  "jev/no-side-effecting-conditional-expression": EvidenceBuilder;
  "jev/no-silent-queue-drop": EvidenceBuilder;
  "jev/no-single-caller-exported-helper": EvidenceBuilder;
  "jev/no-single-use-dependency": EvidenceBuilder;
  "jev/no-singly-owned-lazy-shared-state": EvidenceBuilder;
  "jev/no-skipped-level-import": EvidenceBuilder;
  "jev/no-sleep-in-test": EvidenceBuilder;
  "jev/no-speculative-generality": EvidenceBuilder;
  "jev/no-stability-inversion": EvidenceBuilder;
  "jev/no-stable-surface-widening": EvidenceBuilder;
  "jev/no-stable-to-volatile-edge": EvidenceBuilder;
  "jev/no-stale-binding-use": EvidenceBuilder;
  "jev/no-stale-comment": EvidenceBuilder;
  "jev/no-stale-feature-flag": EvidenceBuilder;
  "jev/no-string-duplicated-enumeration": EvidenceBuilder;
  "jev/no-subclass-fragility-hook": EvidenceBuilder;
  "jev/no-superseded-api-use": EvidenceBuilder;
  "jev/no-swallowed-error": EvidenceBuilder;
  "jev/no-sync-async-sibling-ambiguity": EvidenceBuilder;
  "jev/no-synonym-vocabulary": EvidenceBuilder;
  "jev/no-table-shaped-conditional": EvidenceBuilder;
  "jev/no-team-boundary-crossing": EvidenceBuilder;
  "jev/no-temporal-call-coupling": EvidenceBuilder;
  "jev/no-temporary-field": EvidenceBuilder;
  "jev/no-timezone-naive-arithmetic": EvidenceBuilder;
  "jev/no-transitive-plumbing": EvidenceBuilder;
  "jev/no-transport-coupled-domain": EvidenceBuilder;
  "jev/no-truncating-numeric-parse": EvidenceBuilder;
  "jev/no-twin-gateway-emergence": EvidenceBuilder;
  "jev/no-type-checker-escape": EvidenceBuilder;
  "jev/no-type-code-dispatch": EvidenceBuilder;
  "jev/no-unanchored-domain-check": EvidenceBuilder;
  "jev/no-unawaited-iteration-work": EvidenceBuilder;
  "jev/no-unbounded-accumulation": EvidenceBuilder;
  "jev/no-unbounded-parallel-fanout": EvidenceBuilder;
  "jev/no-unbounded-wait": EvidenceBuilder;
  "jev/no-unchecked-precondition": EvidenceBuilder;
  "jev/no-unclosed-handle": EvidenceBuilder;
  "jev/no-unconstrained-state-string": EvidenceBuilder;
  "jev/no-unconsumed-telemetry": EvidenceBuilder;
  "jev/no-undocumented-contract": EvidenceBuilder;
  "jev/no-unenforced-warning-comment": EvidenceBuilder;
  "jev/no-unexplained-behavioral-literal": EvidenceBuilder;
  "jev/no-unexplained-complex-condition": EvidenceBuilder;
  "jev/no-unexplained-domain-threshold": EvidenceBuilder;
  "jev/no-unexplained-suppression": EvidenceBuilder;
  "jev/no-unguarded-async-init": EvidenceBuilder;
  "jev/no-unguarded-nullable-dereference": EvidenceBuilder;
  "jev/no-unit-ambiguous-quantity": EvidenceBuilder;
  "jev/no-unit-scale-mismatch": EvidenceBuilder;
  "jev/no-unitless-quantity": EvidenceBuilder;
  "jev/no-unlabeled-interactive-element": EvidenceBuilder;
  "jev/no-unlocalized-user-string": EvidenceBuilder;
  "jev/no-unmarked-abandoned-compat-layer": EvidenceBuilder;
  "jev/no-unmeasured-performance-machinery": EvidenceBuilder;
  "jev/no-unmigrated-schema-change": EvidenceBuilder;
  "jev/no-unnamed-parameter-object": EvidenceBuilder;
  "jev/no-unowned-feature-flag": EvidenceBuilder;
  "jev/no-unpinned-boundary-branch": EvidenceBuilder;
  "jev/no-unpinned-compat-quirk": EvidenceBuilder;
  "jev/no-unpinned-failure-path": EvidenceBuilder;
  "jev/no-unreachable-guard": EvidenceBuilder;
  "jev/no-unreleased-subscription": EvidenceBuilder;
  "jev/no-unsafe-redirect-target": EvidenceBuilder;
  "jev/no-unsafe-retry": EvidenceBuilder;
  "jev/no-unsynchronized-shared-memory": EvidenceBuilder;
  "jev/no-untestable-singleton-grab": EvidenceBuilder;
  "jev/no-untrusted-sink-input": EvidenceBuilder;
  "jev/no-unused-exported-helper": EvidenceBuilder;
  "jev/no-unvalidated-boundary-shape": EvidenceBuilder;
  "jev/no-unverified-claim": EvidenceBuilder;
  "jev/no-unverified-mock-contract": EvidenceBuilder;
  "jev/no-unversioned-envelope-change": EvidenceBuilder;
  "jev/no-unwieldy-signature": EvidenceBuilder;
  "jev/no-unwrapped-service-edge": EvidenceBuilder;
  "jev/no-utility-module-grab-bag": EvidenceBuilder;
  "jev/no-utils-grab-bag-growth": EvidenceBuilder;
  "jev/no-variant-partitioned-helper": EvidenceBuilder;
  "jev/no-verbless-function-name": EvidenceBuilder;
  "jev/no-weak-crypto-primitive": EvidenceBuilder;
  "jev/no-wide-fan-in-edit": EvidenceBuilder;
};

const evidenceBuilders: EvidenceRegistry = {
  "jev/no-accidental-serialization": (candidate, projectFiles) =>
    buildAccidentalSerializationEvidence(candidate, projectFiles),
  "jev/no-ad-hoc-branching": (candidate, projectFiles) =>
    buildAdHocBranchingEvidence(candidate, projectFiles),
  "jev/no-adversarial-regex": (candidate, projectFiles) =>
    buildAdversarialRegexEvidence(candidate, projectFiles),
  "jev/no-ambient-dependency-grab": (candidate, projectFiles) =>
    buildAmbientDependencyGrabEvidence(candidate, projectFiles),
  "jev/no-ambiguous-positional-siblings": (candidate, projectFiles) =>
    buildAmbiguousPositionalSiblingsEvidence(candidate, projectFiles),
  "jev/no-anemic-type": (candidate, projectFiles) =>
    buildAnemicTypeEvidence(candidate, projectFiles),
  "jev/no-assertion-free-test": (candidate, projectFiles) =>
    buildAssertionFreeTestEvidence(candidate, projectFiles),
  "jev/no-asymmetric-normalization": (candidate, projectFiles) =>
    buildAsymmetricNormalizationEvidence(candidate, projectFiles),
  "jev/no-avoidable-orchestration": (candidate, projectFiles) =>
    buildAvoidableOrchestrationEvidence(candidate, projectFiles),
  "jev/no-barrel-bypass": (candidate, projectFiles, changes) =>
    buildBarrelBypassEvidence(candidate, projectFiles, changes),
  "jev/no-barrel-wide-reexport": (candidate, projectFiles, changes) =>
    buildBarrelWideReexportEvidence(candidate, changes, projectFiles),
  "jev/no-bespoke-crypto-construction": (candidate, projectFiles) =>
    buildBespokeCryptoConstructionEvidence(candidate, projectFiles),
  "jev/no-blocking-event-loop-call": (candidate, projectFiles) =>
    buildBlockingEventLoopCallEvidence(candidate, projectFiles),
  "jev/no-boolean-fanout": (candidate, projectFiles) =>
    buildBooleanFanoutEvidence(candidate, projectFiles),
  "jev/no-breaking-export-reshape": (candidate, projectFiles, changes) =>
    buildBreakingExportEvidence(candidate, changes, projectFiles),
  "jev/no-call-in-loop-persistence": (candidate, projectFiles) =>
    buildCallInLoopPersistenceEvidence(candidate, projectFiles),
  "jev/no-callback-return-split": (candidate, projectFiles) =>
    buildCallbackReturnSplitEvidence(candidate, projectFiles),
  "jev/no-cascading-fallback": (candidate, projectFiles) =>
    buildCascadingFallbackEvidence(candidate, projectFiles),
  "jev/no-change-amplifier-case": (candidate, projectFiles, changes) =>
    buildChangeAmplifierCaseEvidence(candidate, changes, projectFiles),
  "jev/no-change-stranded-code": (candidate, projectFiles, changes) =>
    buildChangeStrandedCodeEvidence(candidate, changes, projectFiles),
  "jev/no-chatty-interface": (candidate, projectFiles) =>
    buildChattyInterfaceEvidence(candidate, projectFiles),
  "jev/no-check-then-act-race": (candidate, projectFiles) =>
    buildCheckThenActRaceEvidence(candidate, projectFiles),
  "jev/no-clever-expression": (candidate, projectFiles) =>
    buildCleverExpressionEvidence(candidate, projectFiles),
  "jev/no-client-only-authorization": (candidate, projectFiles) =>
    buildClientOnlyAuthorizationEvidence(candidate, projectFiles),
  "jev/no-clone-and-tweak-sibling": (candidate, projectFiles) =>
    buildCloneAndTweakSiblingEvidence(candidate, projectFiles),
  "jev/no-coincidental-similarity": (candidate, projectFiles) =>
    buildCoincidentalSimilarityEvidence(candidate, projectFiles),
  "jev/no-commented-out-implementation": (candidate, projectFiles) =>
    buildCommentedOutImplementationEvidence(candidate, projectFiles),
  "jev/no-complexity-displacement": (candidate, projectFiles, changes) =>
    buildComplexityDisplacementEvidence(candidate, changes, projectFiles),
  "jev/no-concrete-stable-module": (candidate, projectFiles, changes) =>
    buildConcreteStableModuleEvidence(candidate, projectFiles, changes),
  "jev/no-concurrent-shared-mutation": (candidate, projectFiles) =>
    buildConcurrentSharedMutationEvidence(candidate, projectFiles),
  "jev/no-conditionally-valid-state": (candidate, projectFiles) =>
    buildConditionallyValidStateEvidence(candidate, projectFiles),
  "jev/no-confusion-confessing-comment": (candidate, projectFiles) =>
    buildConfusionConfessingCommentEvidence(candidate, projectFiles),
  "jev/no-console-residue": (candidate, projectFiles) =>
    buildConsoleResidueEvidence(candidate, projectFiles),
  "jev/no-construction-in-use": (candidate, projectFiles) =>
    buildConstructionInUseEvidence(candidate, projectFiles),
  "jev/no-context-homonym-type": (candidate, projectFiles) =>
    buildContextHomonymTypeEvidence(candidate, projectFiles),
  "jev/no-contextless-error": (candidate, projectFiles) =>
    buildContextlessErrorEvidence(candidate, projectFiles),
  "jev/no-contract-narrowing-after-ship": (candidate, projectFiles, changes) =>
    buildContractNarrowingEvidence(candidate, changes, projectFiles),
  "jev/no-contract-signature-drift": (candidate, projectFiles) =>
    buildContractSignatureDriftEvidence(candidate, projectFiles),
  "jev/no-convention-breaking-addition": (candidate, projectFiles) =>
    buildConventionBreakingAdditionEvidence(candidate, projectFiles),
  "jev/no-convergent-twin-types": (candidate, projectFiles) =>
    buildConvergentTwinTypesEvidence(candidate, projectFiles),
  "jev/no-correlated-state-booleans": (candidate, projectFiles) =>
    buildCorrelatedStateBooleansEvidence(candidate, projectFiles),
  "jev/no-cross-area-export-break": (candidate, projectFiles, changes) =>
    buildCrossAreaExportBreakEvidence(candidate, projectFiles, changes),
  "jev/no-cross-context-test-reach": (candidate, projectFiles, changes) =>
    buildCrossContextTestReachEvidence(candidate, projectFiles, changes),
  "jev/no-cross-module-call-order": (candidate, projectFiles) =>
    buildCrossModuleCallOrderEvidence(candidate, projectFiles),
  "jev/no-cross-service-source-reach": (candidate, projectFiles, changes) =>
    buildCrossServiceSourceReachEvidence(candidate, projectFiles, changes),
  "jev/no-cryptic-abbreviation": (candidate, projectFiles) =>
    buildCrypticAbbreviationEvidence(candidate, projectFiles),
  "jev/no-data-clump": (candidate, projectFiles) =>
    buildDataClumpEvidence(candidate, projectFiles),
  "jev/no-deceptive-name": (candidate, projectFiles) =>
    buildDeceptiveNameEvidence(candidate, projectFiles),
  "jev/no-deep-delegation-chain": (candidate, projectFiles) =>
    buildDeepDelegationChainEvidence(candidate, projectFiles),
  "jev/no-deep-happy-path-nesting": (candidate, projectFiles) =>
    buildDeepHappyPathNestingEvidence(candidate, projectFiles),
  "jev/no-deployment-coupled-assumption": (candidate, projectFiles) =>
    buildDeploymentCoupledAssumptionEvidence(candidate, projectFiles),
  "jev/no-detached-async-work": (candidate, projectFiles) =>
    buildDetachedAsyncWorkEvidence(candidate, projectFiles),
  "jev/no-dev-dependency-runtime-leak": (candidate, projectFiles) =>
    buildDevDependencyRuntimeLeakEvidence(candidate, projectFiles),
  "jev/no-direction-reversing-edge": (candidate, projectFiles, changes) =>
    buildDirectionReversingEdgeEvidence(candidate, projectFiles, changes),
  "jev/no-disabled-tls-verification": (candidate, projectFiles) =>
    buildDisabledTlsVerificationEvidence(candidate, projectFiles),
  "jev/no-discarded-transformation": (candidate, projectFiles) =>
    buildDiscardedTransformationEvidence(candidate, projectFiles),
  "jev/no-disproportionate-configuration": (candidate, projectFiles) =>
    buildDisproportionateConfigurationEvidence(candidate, projectFiles),
  "jev/no-distrustful-type-guard": (candidate, projectFiles) =>
    buildDistrustfulTypeGuardEvidence(candidate, projectFiles),
  "jev/no-divergent-change": (candidate, projectFiles, changes) =>
    buildDivergentChangeEvidence(candidate, changes, projectFiles),
  "jev/no-divergent-inverses": (candidate, projectFiles) =>
    buildDivergentInversesEvidence(candidate, projectFiles),
  "jev/no-divergent-sibling-interfaces": (candidate, projectFiles) =>
    buildDivergentSiblingInterfacesEvidence(candidate, projectFiles),
  "jev/no-domain-policy-in-adapter": (candidate, projectFiles) =>
    buildDomainPolicyInAdapterEvidence(candidate, projectFiles),
  "jev/no-domain-upward-import": (candidate, projectFiles) =>
    buildDomainUpwardImportEvidence(candidate, projectFiles),
  "jev/no-double-negation": (candidate, projectFiles) =>
    buildDoubleNegationEvidence(candidate, projectFiles),
  "jev/no-doubled-pure-helper": (candidate, projectFiles) =>
    buildDoubledPureHelperEvidence(candidate, projectFiles),
  "jev/no-drilled-prop": (candidate, projectFiles) =>
    buildDrilledPropEvidence(candidate, projectFiles),
  "jev/no-duplicate-config-source": (candidate, projectFiles, changes) =>
    buildDuplicateConfigSourceEvidence(candidate, changes, projectFiles),
  "jev/no-duplicate-module-role": (candidate, projectFiles, changes) =>
    buildDuplicateModuleRoleEvidence(candidate, changes, projectFiles),
  "jev/no-duplicated-fixture-drift": (candidate, projectFiles) =>
    buildDuplicatedFixtureDriftEvidence(candidate, projectFiles),
  "jev/no-duplicated-logic": (candidate, projectFiles) =>
    buildDuplicatedLogicEvidence(candidate, projectFiles),
  "jev/no-duplicated-style-object": (candidate, projectFiles) =>
    buildDuplicatedStyleObjectEvidence(candidate, projectFiles),
  "jev/no-dynamic-code-execution": (candidate, projectFiles) =>
    buildDynamicCodeExecutionEvidence(candidate, projectFiles),
  "jev/no-efferent-coupling-burst": (candidate, projectFiles, changes) =>
    buildEfferentCouplingBurstEvidence(candidate, projectFiles, changes),
  "jev/no-english-only-pluralization": (candidate, projectFiles) =>
    buildEnglishOnlyPluralizationEvidence(candidate, projectFiles),
  "jev/no-entangled-mechanical-change": (candidate, projectFiles, changes) =>
    buildEntangledMechanicalChangeEvidence(candidate, changes, projectFiles),
  "jev/no-excess-context-parameter": (candidate, projectFiles) =>
    buildExcessContextParameterEvidence(candidate, projectFiles),
  "jev/no-falsy-absent-conflation": (candidate, projectFiles) =>
    buildFalsyAbsentConflationEvidence(candidate, projectFiles),
  "jev/no-far-away-test": (candidate, projectFiles, changes) =>
    buildFarAwayTestEvidence(candidate, projectFiles, changes),
  "jev/no-flag-shepherded-control-flow": (candidate, projectFiles) =>
    buildFlagShepherdedControlFlowEvidence(candidate, projectFiles),
  "jev/no-flaky-order-assertion": (candidate, projectFiles) =>
    buildFlakyOrderAssertionEvidence(candidate, projectFiles),
  "jev/no-floating-money-arithmetic": (candidate, projectFiles) =>
    buildFloatingMoneyArithmeticEvidence(candidate, projectFiles),
  "jev/no-foreign-mutation": (candidate, projectFiles) =>
    buildForeignMutationEvidence(candidate, projectFiles),
  "jev/no-fragmented-stateful-procedure": (candidate, projectFiles) =>
    buildFragmentedStatefulProcedureEvidence(candidate, projectFiles),
  "jev/no-fs-recursive-reinvent": (candidate, projectFiles) =>
    buildFsRecursiveReinventEvidence(candidate, projectFiles),
  "jev/no-generic-magic": (candidate, projectFiles) =>
    buildGenericMagicEvidence(candidate, projectFiles),
  "jev/no-giant-test-arrange": (candidate, projectFiles) =>
    buildGiantTestArrangeEvidence(candidate, projectFiles),
  "jev/no-hand-rolled-concurrency-limit": (candidate, projectFiles) =>
    buildHandRolledConcurrencyLimitEvidence(candidate, projectFiles),
  "jev/no-hand-rolled-csv-split": (candidate, projectFiles) =>
    buildHandRolledCsvSplitEvidence(candidate, projectFiles),
  "jev/no-hand-rolled-date-format": (candidate, projectFiles) =>
    buildHandRolledDateFormatEvidence(candidate, projectFiles),
  "jev/no-hand-rolled-debounce": (candidate, projectFiles) =>
    buildHandRolledDebounceEvidence(candidate, projectFiles),
  "jev/no-hand-rolled-deep-clone": (candidate, projectFiles) =>
    buildHandRolledDeepCloneEvidence(candidate, projectFiles),
  "jev/no-hand-rolled-deep-equal": (candidate, projectFiles) =>
    buildHandRolledDeepEqualEvidence(candidate, projectFiles),
  "jev/no-hand-rolled-event-bus": (candidate, projectFiles) =>
    buildHandRolledEventBusEvidence(candidate, projectFiles),
  "jev/no-hand-rolled-fetch-wrapper": (candidate, projectFiles) =>
    buildHandRolledFetchWrapperEvidence(candidate, projectFiles),
  "jev/no-hand-rolled-flatten": (candidate, projectFiles) =>
    buildHandRolledFlattenEvidence(candidate, projectFiles),
  "jev/no-hand-rolled-group-by": (candidate, projectFiles) =>
    buildHandRolledGroupByEvidence(candidate, projectFiles),
  "jev/no-hand-rolled-number-format": (candidate, projectFiles) =>
    buildHandRolledNumberFormatEvidence(candidate, projectFiles),
  "jev/no-hand-rolled-promise-timeout": (candidate, projectFiles) =>
    buildHandRolledPromiseTimeoutEvidence(candidate, projectFiles),
  "jev/no-hand-rolled-relative-time": (candidate, projectFiles) =>
    buildHandRolledRelativeTimeEvidence(candidate, projectFiles),
  "jev/no-hand-rolled-retry-loop": (candidate, projectFiles) =>
    buildHandRolledRetryLoopEvidence(candidate, projectFiles),
  "jev/no-hand-rolled-schema-check": (candidate, projectFiles) =>
    buildHandRolledSchemaCheckEvidence(candidate, projectFiles),
  "jev/no-hand-rolled-set-ops": (candidate, projectFiles) =>
    buildHandRolledSetOpsEvidence(candidate, projectFiles),
  "jev/no-hand-rolled-string-hash": (candidate, projectFiles) =>
    buildHandRolledStringHashEvidence(candidate, projectFiles),
  "jev/no-hand-rolled-url-query": (candidate, projectFiles) =>
    buildHandRolledUrlQueryEvidence(candidate, projectFiles),
  "jev/no-hand-rolled-uuid": (candidate, projectFiles) =>
    buildHandRolledUuidEvidence(candidate, projectFiles),
  "jev/no-hardcoded-config-shadow": (candidate, projectFiles) =>
    buildHardcodedConfigShadowEvidence(candidate, projectFiles),
  "jev/no-heterogeneous-primitive-callers": (candidate, projectFiles) =>
    buildHeterogeneousPrimitiveCallersEvidence(candidate, projectFiles),
  "jev/no-hidden-collaborator-read": (candidate, projectFiles) =>
    buildHiddenCollaboratorReadEvidence(candidate, projectFiles),
  "jev/no-hidden-initialization-order": (candidate, projectFiles) =>
    buildHiddenInitializationOrderEvidence(candidate, projectFiles),
  "jev/no-hidden-input-mutation": (candidate, projectFiles) =>
    buildHiddenInputMutationEvidence(candidate, projectFiles),
  "jev/no-hidden-io": (candidate, projectFiles) =>
    buildHiddenIoEvidence(candidate, projectFiles),
  "jev/no-hidden-loop-exit": (candidate, projectFiles) =>
    buildHiddenLoopExitEvidence(candidate, projectFiles),
  "jev/no-hidden-partial-failure": (candidate, projectFiles) =>
    buildHiddenPartialFailureEvidence(candidate, projectFiles),
  "jev/no-hidden-runtime-input": (candidate, projectFiles) =>
    buildHiddenRuntimeInputEvidence(candidate, projectFiles),
  "jev/no-hollow-delegation-chain": (candidate, projectFiles) =>
    buildHollowDelegationChainEvidence(candidate, projectFiles),
  "jev/no-implementation-mirrored-expectation": (candidate, projectFiles) =>
    buildImplementationMirroredExpectationEvidence(candidate, projectFiles),
  "jev/no-implementation-type-in-signature": (candidate, projectFiles) =>
    buildImplementationTypeInSignatureEvidence(candidate, projectFiles),
  "jev/no-implicit-atomicity": (candidate, projectFiles) =>
    buildImplicitAtomicityEvidence(candidate, projectFiles),
  "jev/no-import-cycle-tangle": (candidate, projectFiles, changes) =>
    buildImportCycleTangleEvidence(candidate, changes, projectFiles),
  "jev/no-import-use-skew": (candidate, projectFiles, changes) =>
    buildImportUseSkewEvidence(candidate, projectFiles, changes),
  "jev/no-impossible-error-branch": (candidate, projectFiles) =>
    buildImpossibleErrorBranchEvidence(candidate, projectFiles),
  "jev/no-inappropriate-intimacy": (candidate, projectFiles) =>
    buildInappropriateIntimacyEvidence(candidate, projectFiles),
  "jev/no-incidental-snapshot": (candidate, projectFiles) =>
    buildIncidentalSnapshotEvidence(candidate, projectFiles),
  "jev/no-inconsistent-error-contract": (candidate, projectFiles) =>
    buildInconsistentErrorContractEvidence(candidate, projectFiles),
  "jev/no-inline-lifecycle-phases": (candidate, projectFiles) =>
    buildInlineLifecyclePhasesEvidence(candidate, projectFiles),
  "jev/no-interaction-pinning-test": (candidate, projectFiles) =>
    buildInteractionPinningTestEvidence(candidate, projectFiles),
  "jev/no-interchangeable-domain-primitives": (candidate, projectFiles) =>
    buildInterchangeableDomainPrimitivesEvidence(candidate, projectFiles),
  "jev/no-inverted-authorization-predicate": (candidate, projectFiles) =>
    buildInvertedAuthorizationPredicateEvidence(candidate, projectFiles),
  "jev/no-knob-multiplicity": (candidate, projectFiles) =>
    buildKnobMultiplicityEvidence(candidate, projectFiles),
  "jev/no-laundered-absence": (candidate, projectFiles) =>
    buildLaunderedAbsenceEvidence(candidate, projectFiles),
  "jev/no-layer-skipping-call": (candidate, projectFiles, changes) =>
    buildLayerSkippingCallEvidence(candidate, projectFiles, changes),
  "jev/no-leaky-internal-export": (candidate, projectFiles) =>
    buildLeakyInternalExportEvidence(candidate, projectFiles),
  "jev/no-live-credential": (candidate, projectFiles) =>
    buildLiveCredentialEvidence(candidate, projectFiles),
  "jev/no-load-bearing-async": (candidate, projectFiles) =>
    buildLoadBearingAsyncEvidence(candidate, projectFiles),
  "jev/no-locale-blind-ordering": (candidate, projectFiles) =>
    buildLocaleBlindOrderingEvidence(candidate, projectFiles),
  "jev/no-locale-date-serialization": (candidate, projectFiles) =>
    buildLocaleDateSerializationEvidence(candidate, projectFiles),
  "jev/no-logic-in-test": (candidate, projectFiles) =>
    buildLogicInTestEvidence(candidate, projectFiles),
  "jev/no-lopsided-error-handling": (candidate, projectFiles) =>
    buildLopsidedErrorHandlingEvidence(candidate, projectFiles),
  "jev/no-lossy-error-translation": (candidate, projectFiles) =>
    buildLossyErrorTranslationEvidence(candidate, projectFiles),
  "jev/no-lossy-sentinel-return": (candidate, projectFiles) =>
    buildLossySentinelReturnEvidence(candidate, projectFiles),
  "jev/no-low-cohesion-class": (candidate, projectFiles) =>
    buildLowCohesionClassEvidence(candidate, projectFiles),
  "jev/no-message-chain": (candidate, projectFiles) =>
    buildMessageChainEvidence(candidate, projectFiles),
  "jev/no-mirrored-derived-state": (candidate, projectFiles) =>
    buildMirroredDerivedStateEvidence(candidate, projectFiles),
  "jev/no-misdirecting-error-message": (candidate, projectFiles) =>
    buildMisdirectingErrorMessageEvidence(candidate, projectFiles),
  "jev/no-misplaced-coordination": (candidate, projectFiles) =>
    buildMisplacedCoordinationEvidence(candidate, projectFiles),
  "jev/no-misplaced-error-boundary": (candidate, projectFiles) =>
    buildMisplacedErrorBoundaryEvidence(candidate, projectFiles),
  "jev/no-missing-health-signal": (candidate, projectFiles) =>
    buildMissingHealthSignalEvidence(candidate, projectFiles),
  "jev/no-missing-shutdown-drain": (candidate, projectFiles) =>
    buildMissingShutdownDrainEvidence(candidate, projectFiles),
  "jev/no-mixed-absence-convention": (candidate, projectFiles) =>
    buildMixedAbsenceConventionEvidence(candidate, projectFiles),
  "jev/no-mixed-abstraction-levels": (candidate, projectFiles) =>
    buildMixedAbstractionLevelsEvidence(candidate, projectFiles),
  "jev/no-mixed-calculation-and-interaction": (candidate, projectFiles) =>
    buildMixedCalculationAndInteractionEvidence(candidate, projectFiles),
  "jev/no-mixed-responsibilities": (candidate, projectFiles) =>
    buildMixedResponsibilitiesEvidence(candidate, projectFiles),
  "jev/no-mock-everything": (candidate, projectFiles) =>
    buildMockEverythingEvidence(candidate, projectFiles),
  "jev/no-mode-flag-parameter": (candidate, projectFiles) =>
    buildModeFlagParameterEvidence(candidate, projectFiles),
  "jev/no-mutable-surface-expansion": (candidate, projectFiles, changes) =>
    buildMutableSurfaceExpansionEvidence(candidate, changes, projectFiles),
  "jev/no-mysterious-name": (candidate, projectFiles) =>
    buildMysteriousNameEvidence(candidate, projectFiles),
  "jev/no-mystery-literal-argument": (candidate, projectFiles, changes) =>
    buildMysteryLiteralArgumentEvidence(candidate, changes, projectFiles),
  "jev/no-needless-abstraction": (candidate, projectFiles) =>
    buildNeedlessAbstractionEvidence(candidate, projectFiles),
  "jev/no-negative-boolean-name": (candidate, projectFiles) =>
    buildNegativeBooleanNameEvidence(candidate, projectFiles),
  "jev/no-nested-conditional-expression": (candidate, projectFiles, changes) =>
    buildNestedConditionalExpressionEvidence(candidate, projectFiles, changes),
  "jev/no-new-foreign-state-write-edge": (candidate, projectFiles, changes) =>
    buildNewForeignStateWriteEdgeEvidence(candidate, projectFiles, changes),
  "jev/no-non-exhaustive-domain-handling": (candidate, projectFiles) =>
    buildNonExhaustiveDomainHandlingEvidence(candidate, projectFiles),
  "jev/no-non-idempotent-retry": (candidate, projectFiles) =>
    buildNonIdempotentRetryEvidence(candidate, projectFiles),
  "jev/no-non-narrowing-guard": (candidate, projectFiles) =>
    buildNonNarrowingGuardEvidence(candidate, projectFiles),
  "jev/no-nondeterministic-test-input": (candidate, projectFiles) =>
    buildNondeterministicTestInputEvidence(candidate, projectFiles),
  "jev/no-offset-pagination-drift": (candidate, projectFiles) =>
    buildOffsetPaginationDriftEvidence(candidate, projectFiles),
  "jev/no-options-style-split": (candidate, projectFiles, changes) =>
    buildOptionsStyleSplitEvidence(candidate, projectFiles, changes),
  "jev/no-orphaned-timer": (candidate, projectFiles) =>
    buildOrphanedTimerEvidence(candidate, projectFiles),
  "jev/no-output-argument": (candidate, projectFiles) =>
    buildOutputArgumentEvidence(candidate, projectFiles),
  "jev/no-overbroad-origin-trust": (candidate, projectFiles) =>
    buildOverbroadOriginTrustEvidence(candidate, projectFiles),
  "jev/no-overload-resolution-ambiguity": (candidate, projectFiles) =>
    buildOverloadResolutionAmbiguityEvidence(candidate, projectFiles),
  "jev/no-overloaded-boolean-return": (candidate, projectFiles) =>
    buildOverloadedBooleanReturnEvidence(candidate, projectFiles),
  "jev/no-oversized-working-set": (candidate, projectFiles) =>
    buildOversizedWorkingSetEvidence(candidate, projectFiles),
  "jev/no-parallel-abstraction": (candidate, projectFiles) =>
    buildParallelAbstractionEvidence(candidate, projectFiles),
  "jev/no-parallel-enumerations": (candidate, projectFiles) =>
    buildParallelEnumerationsEvidence(candidate, projectFiles),
  "jev/no-paraphrased-sibling-logic": (candidate, projectFiles) =>
    buildParaphrasedSiblingLogicEvidence(candidate, projectFiles),
  "jev/no-partially-narrowed-nullable": (candidate, projectFiles) =>
    buildPartiallyNarrowedNullableEvidence(candidate, projectFiles),
  "jev/no-partitioned-fat-interface": (candidate, projectFiles) =>
    buildPartitionedFatInterfaceEvidence(candidate, projectFiles),
  "jev/no-pass-through-wrapper": (candidate, projectFiles) =>
    buildPassThroughWrapperEvidence(candidate, projectFiles),
  "jev/no-path-traversal-join": (candidate, projectFiles) =>
    buildPathTraversalJoinEvidence(candidate, projectFiles),
  "jev/no-persistence-model-leak": (candidate, projectFiles) =>
    buildPersistenceModelLeakEvidence(candidate, projectFiles),
  "jev/no-phantom-member-access": (candidate, projectFiles) =>
    buildPhantomMemberAccessEvidence(candidate, projectFiles),
  "jev/no-phantom-package-import": (candidate, projectFiles) =>
    buildPhantomPackageImportEvidence(candidate, projectFiles),
  "jev/no-positional-extension-drift": (candidate, projectFiles) =>
    buildPositionalExtensionDriftEvidence(candidate, projectFiles),
  "jev/no-pre-gate-side-effect": (candidate, projectFiles) =>
    buildPreGateSideEffectEvidence(candidate, projectFiles),
  "jev/no-predicate-name-deception": (candidate, projectFiles) =>
    buildPredicateNameDeceptionEvidence(candidate, projectFiles),
  "jev/no-predictable-token": (candidate, projectFiles) =>
    buildPredictableTokenEvidence(candidate, projectFiles),
  "jev/no-private-internals-assertion": (candidate, projectFiles) =>
    buildPrivateInternalsAssertionEvidence(candidate, projectFiles),
  "jev/no-promise-combinator-mismatch": (candidate, projectFiles) =>
    buildPromiseCombinatorMismatchEvidence(candidate, projectFiles),
  "jev/no-prototype-in-production": (candidate, projectFiles) =>
    buildPrototypeInProductionEvidence(candidate, projectFiles),
  "jev/no-punned-name": (candidate, projectFiles) =>
    buildPunnedNameEvidence(candidate, projectFiles),
  "jev/no-quarantined-test-coverage": (candidate, projectFiles) =>
    buildQuarantinedTestCoverageEvidence(candidate, projectFiles),
  "jev/no-query-side-effect": (candidate, projectFiles) =>
    buildQuerySideEffectEvidence(candidate, projectFiles),
  "jev/no-rare-case-first": (candidate, projectFiles) =>
    buildRareCaseFirstEvidence(candidate, projectFiles),
  "jev/no-redundant-conditional-arm": (candidate, projectFiles) =>
    buildRedundantConditionalArmEvidence(candidate, projectFiles),
  "jev/no-reentrant-entry": (candidate, projectFiles) =>
    buildReentrantEntryEvidence(candidate, projectFiles),
  "jev/no-refused-inheritance": (candidate, projectFiles) =>
    buildRefusedInheritanceEvidence(candidate, projectFiles),
  "jev/no-repeated-handler-preamble": (candidate, projectFiles) =>
    buildRepeatedHandlerPreambleEvidence(candidate, projectFiles),
  "jev/no-repeated-predicate": (candidate, projectFiles) =>
    buildRepeatedPredicateEvidence(candidate, projectFiles),
  "jev/no-repeated-test-preamble": (candidate, projectFiles) =>
    buildRepeatedTestPreambleEvidence(candidate, projectFiles),
  "jev/no-retained-superseded-implementation": (candidate, projectFiles) =>
    buildRetainedSupersededImplementationEvidence(candidate, projectFiles),
  "jev/no-retry-storm-shape": (candidate, projectFiles) =>
    buildRetryStormEvidence(candidate, projectFiles),
  "jev/no-same-stem-divergent-role": (candidate, projectFiles, changes) =>
    buildSameStemDivergentRoleEvidence(candidate, projectFiles, changes),
  "jev/no-scattered-policy": (candidate, projectFiles) =>
    buildScatteredPolicyEvidence(candidate, projectFiles),
  "jev/no-second-shelf-dependency": (candidate, projectFiles, changes) =>
    buildSecondShelfDependencyEvidence(candidate, projectFiles, changes),
  "jev/no-self-authored-exam": (candidate, projectFiles, changes) =>
    buildSelfAuthoredExamEvidence(candidate, changes, projectFiles),
  "jev/no-sensitive-data-in-log": (candidate, projectFiles) =>
    buildSensitiveDataInLogEvidence(candidate, projectFiles),
  "jev/no-sequential-step-soup": (candidate, projectFiles) =>
    buildSequentialStepSoupEvidence(candidate, projectFiles),
  "jev/no-shadowed-meaning": (candidate, projectFiles) =>
    buildShadowedMeaningEvidence(candidate, projectFiles),
  "jev/no-shallow-convenience-layer": (candidate, projectFiles) =>
    buildShallowConvenienceLayerEvidence(candidate, projectFiles),
  "jev/no-shared-kernel-new-consumer": (candidate, projectFiles, changes) =>
    buildSharedKernelNewConsumerEvidence(candidate, projectFiles, changes),
  "jev/no-shared-mutable-default": (candidate, projectFiles) =>
    buildSharedMutableDefaultEvidence(candidate, projectFiles),
  "jev/no-shared-mutable-module-state": (candidate, projectFiles) =>
    buildSharedMutableModuleStateEvidence(candidate, projectFiles),
  "jev/no-shotgun-change": (candidate, projectFiles, changes) =>
    buildShotgunChangeEvidence(candidate, changes, projectFiles),
  "jev/no-sibling-identifier-swap": (candidate, projectFiles) =>
    buildSiblingIdentifierSwapEvidence(candidate, projectFiles),
  "jev/no-side-effecting-conditional-expression": (candidate, projectFiles) =>
    buildSideEffectingConditionalEvidence(candidate, projectFiles),
  "jev/no-silent-queue-drop": (candidate, projectFiles) =>
    buildSilentQueueDropEvidence(candidate, projectFiles),
  "jev/no-single-caller-exported-helper": (candidate, projectFiles) =>
    buildSingleCallerExportedHelperEvidence(candidate, projectFiles),
  "jev/no-single-use-dependency": (candidate, projectFiles, changes) =>
    buildSingleUseDependencyEvidence(candidate, projectFiles, changes),
  "jev/no-singly-owned-lazy-shared-state": (candidate, projectFiles) =>
    buildSinglyOwnedLazySharedStateEvidence(candidate, projectFiles),
  "jev/no-skipped-level-import": (candidate, projectFiles, changes) =>
    buildSkippedLevelImportEvidence(candidate, projectFiles, changes),
  "jev/no-sleep-in-test": (candidate, projectFiles) =>
    buildSleepInTestEvidence(candidate, projectFiles),
  "jev/no-speculative-generality": (candidate, projectFiles) =>
    buildSpeculativeGeneralityEvidence(candidate, projectFiles),
  "jev/no-stability-inversion": (candidate, projectFiles) =>
    buildStabilityInversionEvidence(candidate, projectFiles),
  "jev/no-stable-surface-widening": (candidate, projectFiles, changes) =>
    buildStableSurfaceWideningEvidence(candidate, projectFiles, changes),
  "jev/no-stable-to-volatile-edge": (candidate, projectFiles, changes) =>
    buildStableToVolatileEdgeEvidence(candidate, projectFiles, changes),
  "jev/no-stale-binding-use": (candidate, projectFiles) =>
    buildStaleBindingUseEvidence(candidate, projectFiles),
  "jev/no-stale-comment": (candidate, projectFiles, changes) =>
    buildStaleCommentEvidence(candidate, projectFiles, changes),
  "jev/no-stale-feature-flag": (candidate, projectFiles) =>
    buildStaleFeatureFlagEvidence(candidate, projectFiles),
  "jev/no-string-duplicated-enumeration": (candidate, projectFiles, changes) =>
    buildStringDuplicatedEnumerationEvidence(candidate, changes, projectFiles),
  "jev/no-subclass-fragility-hook": (candidate, projectFiles) =>
    buildSubclassFragilityHookEvidence(candidate, projectFiles),
  "jev/no-superseded-api-use": (candidate, projectFiles) =>
    buildSupersededApiUseEvidence(candidate, projectFiles),
  "jev/no-swallowed-error": (candidate, projectFiles) =>
    buildSwallowedErrorEvidence(candidate, projectFiles),
  "jev/no-sync-async-sibling-ambiguity": (candidate, projectFiles) =>
    buildSyncAsyncSiblingAmbiguityEvidence(candidate, projectFiles),
  "jev/no-synonym-vocabulary": (candidate, projectFiles) =>
    buildSynonymVocabularyEvidence(candidate, projectFiles),
  "jev/no-table-shaped-conditional": (candidate, projectFiles) =>
    buildTableConditionalEvidence(candidate, projectFiles),
  "jev/no-team-boundary-crossing": (candidate, projectFiles, changes) =>
    buildTeamBoundaryCrossingEvidence(candidate, projectFiles, changes),
  "jev/no-temporal-call-coupling": (candidate, projectFiles) =>
    buildTemporalCallCouplingEvidence(candidate, projectFiles),
  "jev/no-temporary-field": (candidate, projectFiles) =>
    buildTemporaryFieldEvidence(candidate, projectFiles),
  "jev/no-timezone-naive-arithmetic": (candidate, projectFiles) =>
    buildTimezoneNaiveArithmeticEvidence(candidate, projectFiles),
  "jev/no-transitive-plumbing": (candidate, projectFiles) =>
    buildTransitivePlumbingEvidence(candidate, projectFiles),
  "jev/no-transport-coupled-domain": (candidate, projectFiles) =>
    buildTransportCoupledDomainEvidence(candidate, projectFiles),
  "jev/no-truncating-numeric-parse": (candidate, projectFiles) =>
    buildTruncatingNumericParseEvidence(candidate, projectFiles),
  "jev/no-twin-gateway-emergence": (candidate, projectFiles, changes) =>
    buildTwinGatewayEmergenceEvidence(candidate, projectFiles, changes),
  "jev/no-type-checker-escape": (candidate, projectFiles) =>
    buildTypeCheckerEscapeEvidence(candidate, projectFiles),
  "jev/no-type-code-dispatch": (candidate, projectFiles) =>
    buildTypeCodeDispatchEvidence(candidate, projectFiles),
  "jev/no-unanchored-domain-check": (candidate, projectFiles) =>
    buildUnanchoredDomainCheckEvidence(candidate, projectFiles),
  "jev/no-unawaited-iteration-work": (candidate, projectFiles) =>
    buildUnawaitedIterationWorkEvidence(candidate, projectFiles),
  "jev/no-unbounded-accumulation": (candidate, projectFiles) =>
    buildUnboundedAccumulationEvidence(candidate, projectFiles),
  "jev/no-unbounded-parallel-fanout": (candidate, projectFiles) =>
    buildUnboundedParallelFanoutEvidence(candidate, projectFiles),
  "jev/no-unbounded-wait": (candidate, projectFiles) =>
    buildUnboundedWaitEvidence(candidate, projectFiles),
  "jev/no-unchecked-precondition": (candidate, projectFiles) =>
    buildUncheckedPreconditionEvidence(candidate, projectFiles),
  "jev/no-unclosed-handle": (candidate, projectFiles) =>
    buildUnclosedHandleEvidence(candidate, projectFiles),
  "jev/no-unconstrained-state-string": (candidate, projectFiles) =>
    buildUnconstrainedStateStringEvidence(candidate, projectFiles),
  "jev/no-unconsumed-telemetry": (candidate, projectFiles) =>
    buildUnconsumedTelemetryEvidence(candidate, projectFiles),
  "jev/no-undocumented-contract": (candidate, projectFiles) =>
    buildUndocumentedContractEvidence(candidate, projectFiles),
  "jev/no-unenforced-warning-comment": (candidate, projectFiles) =>
    buildUnenforcedWarningCommentEvidence(candidate, projectFiles),
  "jev/no-unexplained-behavioral-literal": (candidate, projectFiles) =>
    buildUnexplainedBehavioralLiteralEvidence(candidate, projectFiles),
  "jev/no-unexplained-complex-condition": (candidate, projectFiles) =>
    buildUnexplainedComplexConditionEvidence(candidate, projectFiles),
  "jev/no-unexplained-domain-threshold": (candidate, projectFiles) =>
    buildUnexplainedDomainThresholdEvidence(candidate, projectFiles),
  "jev/no-unexplained-suppression": (candidate, projectFiles) =>
    buildUnexplainedSuppressionEvidence(candidate, projectFiles),
  "jev/no-unguarded-async-init": (candidate, projectFiles) =>
    buildUnguardedAsyncInitEvidence(candidate, projectFiles),
  "jev/no-unguarded-nullable-dereference": (candidate, projectFiles) =>
    buildUnguardedNullableDereferenceEvidence(candidate, projectFiles),
  "jev/no-unit-ambiguous-quantity": (candidate, projectFiles) =>
    buildUnitAmbiguousQuantityEvidence(candidate, projectFiles),
  "jev/no-unit-scale-mismatch": (candidate, projectFiles) =>
    buildUnitScaleMismatchEvidence(candidate, projectFiles),
  "jev/no-unitless-quantity": (candidate, projectFiles) =>
    buildUnitlessQuantityEvidence(candidate, projectFiles),
  "jev/no-unlabeled-interactive-element": (candidate, projectFiles) =>
    buildUnlabeledInteractiveElementEvidence(candidate, projectFiles),
  "jev/no-unlocalized-user-string": (candidate, projectFiles) =>
    buildUnlocalizedUserStringEvidence(candidate, projectFiles),
  "jev/no-unmarked-abandoned-compat-layer": (candidate, projectFiles) =>
    buildUnmarkedAbandonedCompatLayerEvidence(candidate, projectFiles),
  "jev/no-unmeasured-performance-machinery": (candidate, projectFiles) =>
    buildUnmeasuredPerformanceMachineryEvidence(candidate, projectFiles),
  "jev/no-unmigrated-schema-change": (candidate, projectFiles, changes) =>
    buildUnmigratedSchemaChangeEvidence(candidate, changes, projectFiles),
  "jev/no-unnamed-parameter-object": (candidate, projectFiles) =>
    buildUnnamedParameterObjectEvidence(candidate, projectFiles),
  "jev/no-unowned-feature-flag": (candidate, projectFiles, changes) =>
    buildUnownedFeatureFlagEvidence(candidate, changes, projectFiles),
  "jev/no-unpinned-boundary-branch": (candidate, projectFiles) =>
    buildUnpinnedBoundaryBranchEvidence(candidate, projectFiles),
  "jev/no-unpinned-compat-quirk": (candidate, projectFiles) =>
    buildUnpinnedCompatQuirkEvidence(candidate, projectFiles),
  "jev/no-unpinned-failure-path": (candidate, projectFiles) =>
    buildUnpinnedFailurePathEvidence(candidate, projectFiles),
  "jev/no-unreachable-guard": (candidate, projectFiles) =>
    buildUnreachableGuardEvidence(candidate, projectFiles),
  "jev/no-unreleased-subscription": (candidate, projectFiles) =>
    buildUnreleasedSubscriptionEvidence(candidate, projectFiles),
  "jev/no-unsafe-redirect-target": (candidate, projectFiles) =>
    buildUnsafeRedirectTargetEvidence(candidate, projectFiles),
  "jev/no-unsafe-retry": (candidate, projectFiles) =>
    buildUnsafeRetryEvidence(candidate, projectFiles),
  "jev/no-unsynchronized-shared-memory": (candidate, projectFiles) =>
    buildUnsynchronizedSharedMemoryEvidence(candidate, projectFiles),
  "jev/no-untestable-singleton-grab": (candidate, projectFiles) =>
    buildUntestableSingletonGrabEvidence(candidate, projectFiles),
  "jev/no-untrusted-sink-input": (candidate, projectFiles) =>
    buildUntrustedSinkInputEvidence(candidate, projectFiles),
  "jev/no-unused-exported-helper": (candidate, projectFiles) =>
    buildUnusedExportedHelperEvidence(candidate, projectFiles),
  "jev/no-unvalidated-boundary-shape": (candidate, projectFiles) =>
    buildUnvalidatedBoundaryEvidence(candidate, projectFiles),
  "jev/no-unverified-claim": (candidate, projectFiles) =>
    buildUnverifiedClaimEvidence(candidate, projectFiles),
  "jev/no-unverified-mock-contract": (candidate, projectFiles) =>
    buildUnverifiedMockContractEvidence(candidate, projectFiles),
  "jev/no-unversioned-envelope-change": (candidate, projectFiles, changes) =>
    buildUnversionedEnvelopeChangeEvidence(candidate, changes, projectFiles),
  "jev/no-unwieldy-signature": (candidate, projectFiles) =>
    buildUnwieldySignatureEvidence(candidate, projectFiles),
  "jev/no-unwrapped-service-edge": (candidate, projectFiles, changes) =>
    buildUnwrappedServiceEdgeEvidence(candidate, projectFiles, changes),
  "jev/no-utility-module-grab-bag": (candidate, projectFiles, changes) =>
    buildUtilityModuleGrabBagEvidence(candidate, changes, projectFiles),
  "jev/no-utils-grab-bag-growth": (candidate, projectFiles, changes) =>
    buildUtilsGrabBagGrowthEvidence(candidate, projectFiles, changes),
  "jev/no-variant-partitioned-helper": (candidate, projectFiles) =>
    buildVariantPartitionedHelperEvidence(candidate, projectFiles),
  "jev/no-verbless-function-name": (candidate, projectFiles) =>
    buildVerblessFunctionNameEvidence(candidate, projectFiles),
  "jev/no-weak-crypto-primitive": (candidate, projectFiles) =>
    buildWeakCryptoPrimitiveEvidence(candidate, projectFiles),
  "jev/no-wide-fan-in-edit": (candidate, projectFiles, changes) =>
    buildWideFanInEditEvidence(candidate, changes, projectFiles),
};

export function buildRuleEvidence(
  ruleId: string,
  candidate: Candidate,
  projectFiles: ProjectFile[],
  changes: SourceFile[] = [],
): RuleEvidenceResult {
  // SAFETY: the registry holds one entry per evidence-backed rule from the
  // generator; a miss is an extracted-only or unknown rule, which dispatches
  // as unhandled exactly like the previous if-chain fallthrough.
  const builder = evidenceBuilders[ruleId as keyof EvidenceRegistry];
  if (builder === undefined) {
    return { handled: false };
  }
  return { handled: true, evidence: builder(candidate, projectFiles, changes) };
}
